Repository moonbeam-foundation/moonbeam-docs, pull requests merged in 2023-12, with the labels that each got.

#804 Fix wording
  node-operators/networks/collators/activities.md
Labels: A3 - Quick Fixes

#802 subwallet updates
  images/tokens/connect/subwallet/subwallet-10.png
  images/tokens/connect/subwallet/subwallet-11.png
  images/tokens/connect/subwallet/subwallet-12.png
  images/tokens/connect/subwallet/subwallet-13.png
  images/tokens/connect/subwallet/subwallet-14.png
  images/tokens/connect/subwallet/subwallet-15.png
  images/tokens/connect/subwallet/subwallet-16.png
  images/tokens/connect/subwallet/subwallet-17.png
  images/tokens/connect/subwallet/subwallet-18.png
  images/tokens/connect/subwallet/subwallet-19.png
  images/tokens/connect/subwallet/subwallet-20.png
  images/tokens/connect/subwallet/subwallet-21.png
  images/tokens/connect/subwallet/subwallet-4.png
  images/tokens/connect/subwallet/subwallet-5.png
  images/tokens/connect/subwallet/subwallet-6.png
  images/tokens/connect/subwallet/subwallet-7.png
  images/tokens/connect/subwallet/subwallet-8.png
  images/tokens/connect/subwallet/subwallet-9.png
  tokens/connect/.pages
  tokens/connect/subwallet.md
Labels: A1 - Maintenance Major

#806 Ethers Updates for Tutorials
  .snippets/code/builders/pallets-precompiles/precompiles/batch/Batch.sol
  .snippets/code/tutorials/eth-api/batch-approve-swap/swap.js
  builders/build/eth-api/dev-env/hardhat.md
  tutorials/eth-api/batch-approve-swap.md
  tutorials/eth-api/hardhat-start-to-end.md
  tutorials/eth-api/how-to-build-a-dapp.md
  tutorials/eth-api/randomness-lottery.md
  tutorials/integrations/local-subsquid.md
Labels: A2 - Maintenance Minor

#807 deprecate the remix plugin
  builders/build/eth-api/dev-env/remix.md
  images/builders/build/eth-api/dev-env/remix/using-remix-17.png
  images/builders/build/eth-api/dev-env/remix/using-remix-18.png
Labels: A3 - Quick Fixes

#811 bump client to v0.34.1 and spec version to 2601
  builders/interoperability/xcm/fees.md
  builders/interoperability/xcm/remote-evm-calls.md
  builders/interoperability/xcm/xc20/xtokens.md
  variables.yml
Labels: A2 - Maintenance Minor

#810 clean up a few tiny fixes
  .snippets/code/builders/build/eth-api/libraries/web3-py/balances.py
  builders/get-started/networks/moonbeam-dev.md
  builders/integrations/oracles/api3.md
  builders/interoperability/xcm/xcm-sdk/v1/xcm-sdk.md
Labels: A3 - Quick Fixes

#814 Update Remix Video Embed
  builders/build/eth-api/dev-env/remix.md
Labels: A3 - Quick Fixes

#813 update polkadot.js apps examples to use polkadot.js api
  .snippets/code/builders/get-started/eth-compare/balances/balance.js
  .snippets/code/builders/get-started/eth-compare/balances/locks.js
  builders/get-started/eth-compare/balances.md
Labels: A2 - Maintenance Minor

#812 Misc changes: Add more XCM SDK examples, add Web3.js common errors, and a few quick fixes
  .snippets/code/builders/build/eth-api/libraries/web3-js/deploy.js
  .snippets/code/builders/build/eth-api/libraries/web3-js/get.js
  .snippets/code/builders/build/eth-api/libraries/web3-js/increment.js
  .snippets/code/builders/build/eth-api/libraries/web3-js/reset.js
  .snippets/code/builders/build/eth-api/libraries/web3-js/transaction.js
  .snippets/text/_common/assumes-mac-or-ubuntu-env.md
  .snippets/text/learn/features/governance/approval-support-definitions.md
  .snippets/text/learn/features/governance/delegation-definitions.md
  .snippets/text/learn/features/governance/vote-conviction-definitions.md
  builders/build/eth-api/libraries/web3js.md
  builders/interoperability/xcm/xcm-sdk/v1/xcm-sdk.md
  node-operators/networks/run-a-node/flags.md
  tokens/governance/voting.md
Labels: A1 - Maintenance Major

#815 Update PR checklist to include adding a label
  .github/pull-request-template.md
Labels: A3 - Quick Fixes

#797 xcm transactor v3 on moonbeam and moonriver
  .snippets/code/builders/interoperability/xcm/remote-execution/substrate-calls/xcm-transactor-precompile/XcmTransactorV3ABI.js
  .snippets/code/builders/interoperability/xcm/remote-execution/substrate-calls/xcm-transactor-precompile/transact-through-signed/ethers.js
  .snippets/code/builders/interoperability/xcm/remote-execution/substrate-calls/xcm-transactor-precompile/transact-through-signed/web3.js
  .snippets/code/builders/interoperability/xcm/remote-execution/substrate-calls/xcm-transactor-precompile/transact-through-signed/web3.py
  builders/build/canonical-contracts.md
  builders/interoperability/xcm/remote-execution/substrate-calls/xcm-transactor-precompile.md
  builders/pallets-precompiles/precompiles/overview.md
Labels: A2 - Maintenance Minor

#817 Update coinbase wallet images
  images/tokens/connect/coinbase-wallet/coinbase-1.png
  images/tokens/connect/coinbase-wallet/coinbase-2.png
  images/tokens/connect/coinbase-wallet/coinbase-3.png
  images/tokens/connect/coinbase-wallet/coinbase-4.png
  images/tokens/connect/coinbase-wallet/coinbase-5.png
  images/tokens/connect/coinbase-wallet/coinbase-6.png
  images/tokens/connect/coinbase-wallet/coinbase-7.png
  images/tokens/connect/coinbase-wallet/coinbase-wallet-1.png
  images/tokens/connect/coinbase-wallet/coinbase-wallet-2.png
  images/tokens/connect/coinbase-wallet/coinbase-wallet-3.png
  images/tokens/connect/coinbase-wallet/coinbase-wallet-4.png
  images/tokens/connect/coinbase-wallet/coinbase-wallet-5.png
  tokens/connect/coinbase-wallet.md
Labels: A3 - Quick Fixes

#816 update scaffold-eth docs to v2
  builders/build/eth-api/dev-env/scaffold-eth.md
  images/builders/build/eth-api/dev-env/scaffold-eth/new/scaffold-eth-1.png
  images/builders/build/eth-api/dev-env/scaffold-eth/new/scaffold-eth-2.png
  images/builders/build/eth-api/dev-env/scaffold-eth/new/scaffold-eth-3.png
  images/builders/build/eth-api/dev-env/scaffold-eth/new/scaffold-eth-4.png
  images/builders/build/eth-api/dev-env/scaffold-eth/new/scaffold-eth-5.png
Labels: A1 - Maintenance Major

#819 add hidden page for runtime upgrades
  builders/build/runtime-upgrades.md
Labels: A0 - New Content

#822 Removed Runtime Specific URL
  builders/build/runtime-upgrades.md
Labels: A3 - Quick Fixes

#823 update and generalize subquery docs
  builders/integrations/indexers/subquery.md
  builders/integrations/indexers/subsquid.md
  images/builders/integrations/indexers/subquery/new/subquery-1.png
  images/builders/integrations/indexers/subquery/new/subquery-2.png
  images/builders/integrations/indexers/subquery/new/subquery-3.png
  images/builders/integrations/indexers/subquery/new/subquery-4.png
  images/builders/integrations/indexers/subquery/new/subquery-5.png
  images/builders/integrations/indexers/subquery/new/subquery-6.png
  images/builders/integrations/indexers/subquery/new/subquery-7.png
  images/builders/integrations/indexers/subquery/new/subquery-8.png
Labels: A1 - Maintenance Major

#821 apply some minor fixes to covalent docs
  builders/integrations/indexers/covalent.md
Labels: A3 - Quick Fixes

#824 add xcPDEX and xcPEN to list of Moonbeam xc-20s
  builders/interoperability/xcm/xc20/overview.md
Labels: A3 - Quick Fixes
