Repository moonbeam-foundation/moonbeam-docs, pull requests merged in 2023-10, with the labels that each got.

#765 update xcm-related snippets
  .snippets/code/builders/interoperability/xcm/xc20/overview/local-xc20s/ethers.js
  .snippets/code/builders/interoperability/xcm/xc20/overview/local-xc20s/web3.js
  .snippets/code/builders/interoperability/xcm/xc20/overview/local-xc20s/web3.py
  .snippets/code/builders/pallets-precompiles/precompiles/xcm-transactor/XcmTransactorV1.sol
  .snippets/code/builders/pallets-precompiles/precompiles/xcm-transactor/XcmTransactorV2.sol
  .snippets/code/builders/pallets-precompiles/precompiles/xcm-transactor/XcmTransactorV3.sol
  .snippets/text/builders/interoperability/xcm/xc20/x-tokens/xcm-instructions.md
  builders/interoperability/xcm/fees.md
  builders/interoperability/xcm/xc20/overview.md
  builders/interoperability/xcm/xc20/xtokens.md
  builders/interoperability/xcm/xcm-transactor.md
Labels: A2 - Maintenance Minor

#768 Minor Hardhat Updates
  builders/build/eth-api/dev-env/foundry.md
  builders/build/eth-api/dev-env/hardhat.md
  tutorials/eth-api/hardhat-start-to-end.md
Labels: A3 - Quick Fixes

#749 add info on mbip-5 to the key differences section
  builders/get-started/eth-compare/tx-fees.md
  variables.yml
Labels: A0 - New Content, A2 - Maintenance Minor

#769 Update DIA docs
  builders/integrations/oracles/.pages
  builders/integrations/oracles/dia.md
Labels: A0 - New Content

#763 add sql node docs
  .snippets/text/node-operators/networks/run-a-node/client-changes.md
  .snippets/text/node-operators/networks/run-a-node/external-access.md
  .snippets/text/node-operators/networks/run-a-node/post-purge.md
  .snippets/text/node-operators/networks/run-a-node/sql-backend.md
  .snippets/text/node-operators/networks/run-a-node/systemd/run-service.md
  images/node-operators/networks/run-a-node/compile-binary/full-node-binary-1.png
  images/node-operators/networks/run-a-node/compile-binary/full-node-binary-2.png
  images/node-operators/networks/run-a-node/compile-binary/full-node-binary-3.png
  images/node-operators/networks/run-a-node/docker/full-node-docker-1.png
  images/node-operators/networks/run-a-node/docker/full-node-docker-2.png
  images/node-operators/networks/run-a-node/systemd/systemd-1.png
  images/node-operators/networks/run-a-node/systemd/systemd-2.png
  node-operators/networks/run-a-node/compile-binary.md
  node-operators/networks/run-a-node/docker.md
  node-operators/networks/run-a-node/flags.md
  node-operators/networks/run-a-node/systemd.md
  node-operators/networks/tracing-node.md
Labels: A0 - New Content, A1 - Maintenance Major

#773 fix xcm sdk snippets
  builders/interoperability/xcm/xcm-sdk/v1/xcm-sdk.md
Labels: A2 - Maintenance Minor

#770 Remove truffle
  builders/build/eth-api/dev-env/.pages
  builders/build/eth-api/dev-env/index.md
  builders/build/eth-api/dev-env/openzeppelin/defender.md
  builders/build/eth-api/dev-env/truffle.md
  builders/build/eth-api/dev-env/waffle-mars.md
  builders/build/eth-api/verify-contracts/block-explorers.md
  builders/build/eth-api/verify-contracts/etherscan-plugins.md
  builders/get-started/quick-start.md
  builders/get-started/token-profile.md
  learn/features/eth-compatibility.md
  learn/platform/links.md
  learn/platform/technology.md
  learn/platform/vision.md
  tutorials/eth-api/.pages
  tutorials/eth-api/truffle-start-to-end.md
Labels: A2 - Maintenance Minor

#775 XCM Transactor & Chopsticks Fixes
  builders/build/substrate-api/chopsticks.md
  builders/integrations/indexers/subsquid.md
  builders/interoperability/xcm/xcm-transactor.md
Labels: A2 - Maintenance Minor

#774 remove truffle images
  builders/build/eth-api/verify-contracts/etherscan-plugins.md
  images/builders/build/eth-api/dev-env/truffle/truffle-1.png
  images/builders/build/eth-api/dev-env/truffle/truffle-2.png
  images/builders/build/eth-api/dev-env/truffle/truffle-3.png
  images/builders/build/eth-api/dev-env/truffle/truffle-4.png
  images/builders/build/eth-api/dev-env/truffle/truffle-5.png
  images/builders/build/eth-api/dev-env/truffle/truffle-6.png
  images/builders/build/eth-api/dev-env/truffle/truffle-7.png
  images/builders/build/eth-api/dev-env/truffle/truffle-8.png
  images/builders/build/eth-api/verify-contracts/etherscan-plugins/plugins-4.png
  images/builders/build/eth-api/verify-contracts/etherscan-plugins/plugins-5.png
  images/builders/build/eth-api/verify-contracts/etherscan-plugins/plugins-6.png
  images/tutorials/eth-api/truffle-start-to-end/truffle-1.png
  images/tutorials/eth-api/truffle-start-to-end/truffle-10.png
  images/tutorials/eth-api/truffle-start-to-end/truffle-11.png
  images/tutorials/eth-api/truffle-start-to-end/truffle-12.png
  images/tutorials/eth-api/truffle-start-to-end/truffle-2.png
  images/tutorials/eth-api/truffle-start-to-end/truffle-3.png
  images/tutorials/eth-api/truffle-start-to-end/truffle-4.png
  images/tutorials/eth-api/truffle-start-to-end/truffle-5.png
  images/tutorials/eth-api/truffle-start-to-end/truffle-6.png
  images/tutorials/eth-api/truffle-start-to-end/truffle-7.png
  images/tutorials/eth-api/truffle-start-to-end/truffle-8.png
  images/tutorials/eth-api/truffle-start-to-end/truffle-9.png
Labels: A3 - Quick Fixes

#776 remove onFinality Public endpoint
  .snippets/code/tutorials/integrations/nft-subsquid/contract.ts
  .snippets/text/builders/get-started/endpoints/moonbase.md
  .snippets/text/builders/get-started/endpoints/moonbeam.md
  .snippets/text/builders/get-started/endpoints/moonriver.md
  builders/get-started/endpoints.md
  builders/get-started/quick-start.md
Labels: A3 - Quick Fixes
