Repository moonbeam-foundation/moonbeam-docs, pull requests merged in 2023-09, with the labels that each got.

#734 Updates to Ethers.js Page
  .snippets/code/ethers-contract-local/reset.js
  .snippets/code/ethers-js-contract/deploy.js
  .snippets/code/ethers-js-contract/get.js
  .snippets/code/ethers-js-contract/increment.js
  .snippets/code/ethers-js-contract/reset.js
  .snippets/code/ethers-js-tx/balances.js
  .snippets/code/ethers-js-tx/transaction.js
  .snippets/code/ethers-tx-local/balances.js
  .snippets/code/ethers-tx-local/transaction.js
  .snippets/code/web3-contract-local/deploy.js
  .snippets/code/web3-contract-local/get.js
  .snippets/code/web3-contract-local/increment.js
  .snippets/code/web3-contract-local/reset.js
  .snippets/code/web3-tx-local/balances.js
  .snippets/code/web3-tx-local/transaction.js
  .snippets/code/web3py-contract/deploy.py
  .snippets/code/web3py-contract/get.py
  .snippets/code/web3py-contract/increment.py
  .snippets/code/web3py-contract/reset.py
  .snippets/code/web3py-tx/balances.py
  .snippets/code/web3py-tx/transaction.py
  builders/build/eth-api/libraries/ethersjs.md
  builders/build/eth-api/libraries/web3js.md
  builders/get-started/eth-compare/consensus-finality.md
  builders/integrations/wallets/walletconnect.md
  builders/interoperability/xcm/xcm-sdk/v0/xcm-sdk.md
  builders/pallets-precompiles/precompiles/call-permit.md
  tutorials/integrations/nft-subsquid.md
Labels: A2 - Maintenance Minor

#741 RT2500 Staking Changes
  .snippets/code/precompiles/staking/StakingInterface.sol
  builders/pallets-precompiles/pallets/staking.md
  builders/pallets-precompiles/precompiles/staking.md
Labels: A2 - Maintenance Minor

#737 move macos snippets to be expandable & update tracing tag
  .snippets/text/full-node/macos-node.md
  builders/interoperability/xcm/fees.md
  builders/interoperability/xcm/remote-evm-calls.md
  builders/interoperability/xcm/send-execute-xcm.md
  builders/interoperability/xcm/xc20/xtokens.md
  node-operators/networks/run-a-node/docker.md
  node-operators/networks/run-a-node/systemd.md
  node-operators/networks/tracing-node.md
  variables.yml
Labels: A2 - Maintenance Minor

#740 update docs for ws/rpc changes
  .snippets/text/node-operators/client-changes.md
  builders/get-started/networks/moonbeam-dev.md
  node-operators/networks/run-a-node/docker.md
  node-operators/networks/run-a-node/flags.md
  node-operators/networks/run-a-node/overview.md
  node-operators/networks/run-a-node/systemd.md
  node-operators/networks/tracing-node.md
  tutorials/integrations/local-subsquid.md
  variables.yml
Labels: A2 - Maintenance Minor

#739 Updates to Web3.py Page
  .snippets/code/web3py-contract/deploy.py
  .snippets/code/web3py-contract/get.py
  .snippets/code/web3py-contract/increment.py
  .snippets/code/web3py-contract/reset.py
  .snippets/code/web3py-tx/balances.py
  .snippets/code/web3py-tx/transaction.py
  builders/build/eth-api/libraries/web3js.md
  builders/build/eth-api/libraries/web3py.md
Labels: A2 - Maintenance Minor

#745 Updates Metamask Page with new steps
  images/tokens/connect/metamask/new/metamask-1.png
  images/tokens/connect/metamask/new/metamask-10.png
  images/tokens/connect/metamask/new/metamask-11.png
  images/tokens/connect/metamask/new/metamask-12.png
  images/tokens/connect/metamask/new/metamask-13.png
  images/tokens/connect/metamask/new/metamask-14.png
  images/tokens/connect/metamask/new/metamask-2.png
  images/tokens/connect/metamask/new/metamask-3.png
  images/tokens/connect/metamask/new/metamask-4.png
  images/tokens/connect/metamask/new/metamask-5.png
  images/tokens/connect/metamask/new/metamask-6.png
  images/tokens/connect/metamask/new/metamask-7.png
  images/tokens/connect/metamask/new/metamask-8.png
  images/tokens/connect/metamask/new/metamask-9.png
  tokens/connect/metamask.md
Labels: A1 - Maintenance Major

#751 remove blockscout
  .snippets/text/explorers/explorers.md
  builders/build/eth-api/debug-trace.md
  builders/build/eth-api/verify-contracts/block-explorers.md
  builders/get-started/explorers.md
  builders/get-started/networks/moonbase.md
  builders/get-started/networks/moonbeam.md
  builders/get-started/networks/moonriver.md
  images/builders/build/eth-api/verify-contracts/block-explorers/verify-contract-6.png
  images/builders/build/eth-api/verify-contracts/block-explorers/verify-contract-7.png
  images/builders/build/eth-api/verify-contracts/block-explorers/verify-contract-8.png
  images/builders/build/eth-api/verify-contracts/block-explorers/verify-contract-9.png
  images/builders/get-started/explorers/explorers-2.png
  images/builders/get-started/explorers/explorers-3.png
  images/builders/get-started/explorers/explorers-4.png
  images/builders/get-started/explorers/explorers-5.png
  images/builders/get-started/explorers/explorers-6.png
  node-operators/networks/tracing-node.md
Labels: A2 - Maintenance Minor

#747 Update XCM SDK docs for ethersSigner to evmSigner changes
  builders/interoperability/xcm/xcm-sdk/v1/reference.md
  builders/interoperability/xcm/xcm-sdk/v1/xcm-sdk.md
Labels: A2 - Maintenance Minor

#753 update grammar on block explorers page
  builders/build/eth-api/verify-contracts/block-explorers.md
Labels: A3 - Quick Fixes

#756 update subsquid branding info
  builders/integrations/indexers/subsquid.md
  tutorials/integrations/local-subsquid.md
  tutorials/integrations/nft-subsquid.md
Labels: A2 - Maintenance Minor

#755 Adding extra contents for MacOS
  builders/get-started/networks/moonbeam-dev.md
Labels: A3 - Quick Fixes

#742 update the gmp precompile as it now accepts a v2 user versioned action
  .snippets/code/precompiles/gmp/v1-payload.ts
  .snippets/code/precompiles/gmp/v2-payload.ts
  builders/pallets-precompiles/precompiles/gmp.md
Labels: A2 - Maintenance Minor

#744 add section on overriding local xc-20 transfer gas limits
  builders/interoperability/xcm/xc20/xtokens.md
Labels: A2 - Maintenance Minor

#748 add identity precompile and pallet docs
  .snippets/code/precompiles/identity/Identity.sol
  .snippets/code/precompiles/identity/abi.js
  .snippets/code/precompiles/identity/ethers.js
  .snippets/code/precompiles/identity/web3.js
  .snippets/code/precompiles/identity/web3.py
  .snippets/code/precompiles/registry/web3.py
  builders/pallets-precompiles/pallets/.pages
  builders/pallets-precompiles/pallets/identity.md
  builders/pallets-precompiles/precompiles/.pages
  builders/pallets-precompiles/precompiles/identity.md
  variables.yml
Labels: A0 - New Content

#761 Foundry Verification fix
  builders/build/eth-api/dev-env/foundry.md
  builders/build/eth-api/verify-contracts/etherscan-plugins.md
Labels: A3 - Quick Fixes

#762 add missing import from viem snippets
  builders/build/eth-api/libraries/viem.md
Labels: A3 - Quick Fixes

#760 update rpc support
  .snippets/code/vs-ethereum/consensus-finality/custom-rpc/web3.py
  builders/build/eth-api/debug-trace.md
  builders/build/eth-api/dev-env/hardhat.md
  builders/build/eth-api/libraries/ethersjs.md
  builders/build/eth-api/libraries/ethersrs.md
  builders/build/eth-api/libraries/web3js.md
  builders/build/eth-api/libraries/web3py.md
  builders/build/moonbeam-custom-api.md
  builders/build/substrate-api/py-substrate-interface.md
  builders/get-started/endpoints.md
  builders/get-started/eth-compare/consensus-finality.md
  builders/get-started/eth-compare/rpc-support.md
  builders/get-started/eth-compare/transfers-api.md
  builders/get-started/networks/moonbeam-dev.md
  builders/interoperability/xcm/remote-evm-calls.md
Labels: A2 - Maintenance Minor

#758 Add clarification around a few misc items (Kapa feedback)
  .snippets/code/xc20/local-xc20s/ethers.js
  .snippets/code/xc20/local-xc20s/web3.js
  .snippets/code/xc20/local-xc20s/web3.py
  .snippets/text/x-tokens/xcm-instructions.md
  builders/interoperability/xcm/fees.md
  builders/interoperability/xcm/xc-registration/assets.md
  builders/interoperability/xcm/xc20/overview.md
  builders/interoperability/xcm/xc20/xtokens.md
Labels: A2 - Maintenance Minor

#743 add xcm transactor v3 docs
  .snippets/code/precompiles/xcm-transactor/XcmTransactorV1.sol
  .snippets/code/precompiles/xcm-transactor/XcmTransactorV2.sol
  .snippets/code/precompiles/xcm-transactor/XcmTransactorV3.sol
  builders/build/canonical-contracts.md
  builders/interoperability/xcm/xcm-transactor.md
  builders/pallets-precompiles/precompiles/overview.md
  variables.yml
Labels: A0 - New Content, A1 - Maintenance Major

#764 fix snippets
  .snippets/text/_common/install-nodejs.md
  builders/build/eth-api/dev-env/brownie.md
  builders/build/eth-api/dev-env/foundry.md
  builders/build/eth-api/dev-env/hardhat.md
  builders/build/eth-api/dev-env/remix.md
  builders/build/eth-api/dev-env/waffle-mars.md
  builders/build/eth-api/libraries/ethersrs.md
  builders/build/substrate-api/py-substrate-interface.md
  builders/interoperability/xcm/xc20/xtokens.md
  builders/interoperability/xcm/xcm-transactor.md
  builders/pallets-precompiles/precompiles/author-mapping.md
  builders/pallets-precompiles/precompiles/batch.md
  builders/pallets-precompiles/precompiles/call-permit.md
  builders/pallets-precompiles/precompiles/collective.md
  builders/pallets-precompiles/precompiles/conviction-voting.md
  builders/pallets-precompiles/precompiles/erc20.md
  builders/pallets-precompiles/precompiles/overview.md
  builders/pallets-precompiles/precompiles/preimage.md
  builders/pallets-precompiles/precompiles/proxy.md
  builders/pallets-precompiles/precompiles/randomness.md
  builders/pallets-precompiles/precompiles/referenda.md
  builders/pallets-precompiles/precompiles/registry.md
  builders/pallets-precompiles/precompiles/staking.md
  builders/pallets-precompiles/precompiles/xcm-utils.md
  node-operators/oracle-nodes/node-chainlink.md
  tutorials/eth-api/batch-approve-swap.md
  tutorials/eth-api/call-permit-gasless-txs.md
  tutorials/eth-api/foundry-start-to-end.md
  tutorials/eth-api/hardhat-start-to-end.md
Labels: A2 - Maintenance Minor
