Repository moonbeam-foundation/moonbeam-docs, pull requests merged in 2023-11, with the labels that each got.

#779 remove gelato docs and relayers section
  builders/integrations/.pages
  builders/integrations/relayers/.pages
  builders/integrations/relayers/gelato.md
  builders/integrations/relayers/index.md
  images/builders/integrations/relayers/gelato/gelato-1.png
  images/builders/integrations/relayers/gelato/gelato-2.png
  images/builders/integrations/relayers/gelato/gelato-3.png
  images/builders/integrations/relayers/gelato/gelato-4.png
  images/builders/integrations/relayers/gelato/gelato-5.png
Labels: A3 - Quick Fixes

#780 update the web3.js docs
  .snippets/code/builders/build/eth-api/libraries/web3-js/balances.js
  .snippets/code/builders/build/eth-api/libraries/web3-js/deploy.js
  .snippets/code/builders/build/eth-api/libraries/web3-js/get.js
  .snippets/code/builders/build/eth-api/libraries/web3-js/increment.js
  .snippets/code/builders/build/eth-api/libraries/web3-js/reset.js
  .snippets/code/builders/build/eth-api/libraries/web3-js/transaction.js
  .snippets/code/builders/get-started/eth-compare/consensus-finality/custom-rpc/web3.js
  .snippets/code/builders/get-started/eth-compare/consensus-finality/web3.js
  .snippets/code/builders/interoperability/xcm/send-execute-xcm/execute/web3.js
  .snippets/code/builders/interoperability/xcm/send-execute-xcm/send/web3.js
  .snippets/code/builders/interoperability/xcm/xc20/overview/local-xc20s/web3.js
  .snippets/code/builders/interoperability/xcm/xc20/xtokens/web3.js
  .snippets/code/builders/pallets-precompiles/precompiles/eth-mainnet/ecrecover.js
  .snippets/code/builders/pallets-precompiles/precompiles/identity/web3.js
  .snippets/code/builders/pallets-precompiles/precompiles/registry/web3.js
  .snippets/text/builders/get-started/networks/moonbase/connect.md
  .snippets/text/builders/get-started/networks/moonbeam/connect.md
  .snippets/text/builders/get-started/networks/moonriver/connect.md
  builders/build/eth-api/libraries/web3js.md
  builders/build/eth-api/pubsub.md
Labels: A2 - Maintenance Minor

#784 update consensus and finality page
  .snippets/code/builders/get-started/eth-compare/consensus-finality/custom-rpc/block/ethers.js
  .snippets/code/builders/get-started/eth-compare/consensus-finality/custom-rpc/block/web3.js
  .snippets/code/builders/get-started/eth-compare/consensus-finality/custom-rpc/block/web3.py
  .snippets/code/builders/get-started/eth-compare/consensus-finality/custom-rpc/tx/ethers.js
  .snippets/code/builders/get-started/eth-compare/consensus-finality/custom-rpc/tx/web3.js
  .snippets/code/builders/get-started/eth-compare/consensus-finality/custom-rpc/tx/web3.py
  builders/get-started/eth-compare/consensus-finality.md
Labels: A2 - Maintenance Minor

#782 update the remix docs
  .snippets/code/builders/build/eth-api/dev-env/remix/MyToken.sol
  builders/build/eth-api/dev-env/remix.md
  images/builders/build/eth-api/dev-env/remix/new/remix-1.png
  images/builders/build/eth-api/dev-env/remix/new/remix-10.png
  images/builders/build/eth-api/dev-env/remix/new/remix-11.png
  images/builders/build/eth-api/dev-env/remix/new/remix-12.png
  images/builders/build/eth-api/dev-env/remix/new/remix-13.png
  images/builders/build/eth-api/dev-env/remix/new/remix-14.png
  images/builders/build/eth-api/dev-env/remix/new/remix-2.png
  images/builders/build/eth-api/dev-env/remix/new/remix-3.png
  images/builders/build/eth-api/dev-env/remix/new/remix-4.png
  images/builders/build/eth-api/dev-env/remix/new/remix-5.png
  images/builders/build/eth-api/dev-env/remix/new/remix-6.png
  images/builders/build/eth-api/dev-env/remix/new/remix-7.png
  images/builders/build/eth-api/dev-env/remix/new/remix-8.png
  images/builders/build/eth-api/dev-env/remix/new/remix-9.png
  images/tokens/connect/metamask/new/metamask-15.png
  images/tokens/connect/metamask/new/metamask-16.png
  images/tokens/connect/metamask/new/metamask-17.png
  images/tokens/connect/metamask/new/metamask-18.png
  images/tokens/connect/metamask/new/metamask-19.png
  tokens/connect/metamask.md
Labels: A1 - Maintenance Major

#785 update hardhat docs
  builders/build/eth-api/dev-env/hardhat.md
  images/builders/build/eth-api/dev-env/hardhat/hardhat-1.png
  images/builders/build/eth-api/dev-env/hardhat/hardhat-2.png
  images/builders/build/eth-api/dev-env/hardhat/hardhat-3.png
  images/builders/build/eth-api/dev-env/hardhat/hardhat-4.png
  images/builders/build/eth-api/dev-env/hardhat/hardhat-5-new.png
Labels: A1 - Maintenance Major

#788 remove mintable xc-20 docs
  builders/get-started/eth-compare/security.md
  builders/interoperability/xcm/xc20/mintable-xc20.md
  builders/interoperability/xcm/xc20/xtokens.md
  variables.yml
Labels: A2 - Maintenance Minor

#792 update kusama fees to v1.0.0 and rollback polkadot links to v0.9.43
  .snippets/text/builders/interoperability/xcm/xc20/x-tokens/xcm-instructions.md
  builders/interoperability/xcm/fees.md
  builders/interoperability/xcm/xc20/xtokens.md
  variables.yml
Labels: A2 - Maintenance Minor

#794 add subwallet docs
  images/tokens/connect/subwallet/subwallet-1.png
  images/tokens/connect/subwallet/subwallet-10.png
  images/tokens/connect/subwallet/subwallet-11.png
  images/tokens/connect/subwallet/subwallet-12.png
  images/tokens/connect/subwallet/subwallet-13.png
  images/tokens/connect/subwallet/subwallet-14.png
  images/tokens/connect/subwallet/subwallet-15.png
  images/tokens/connect/subwallet/subwallet-2.png
  images/tokens/connect/subwallet/subwallet-3.png
  images/tokens/connect/subwallet/subwallet-4.png
  images/tokens/connect/subwallet/subwallet-5.png
  images/tokens/connect/subwallet/subwallet-6.png
  images/tokens/connect/subwallet/subwallet-7.png
  images/tokens/connect/subwallet/subwallet-8.png
  images/tokens/connect/subwallet/subwallet-9.png
  tokens/connect/.pages
  tokens/connect/subwallet.md
Labels: A0 - New Content

#795 bump to client v0.34.0 and switch purestake to moonbeamfoundation
  builders/get-started/networks/moonbeam-dev.md
  node-operators/networks/run-a-node/docker.md
  node-operators/networks/run-a-node/flags.md
  node-operators/networks/tracing-node.md
  tutorials/integrations/local-subsquid.md
  variables.yml
Labels: A2 - Maintenance Minor

#796 Fix Typos
  js/connectMetaMask.js
  learn/features/eth-compatibility.md
  tokens/connect/ledger/moonbeam.md
  tokens/connect/ledger/moonriver.md
Labels: A3 - Quick Fixes

#793 New Subsquid Tutorial for Local ERC-20 Indexing on Local Dev Node
  .snippets/code/tutorials/integrations/local-subsquid/MyTok.sol
  .snippets/code/tutorials/integrations/local-subsquid/deploy.js
  .snippets/code/tutorials/integrations/local-subsquid/erc20.json
  .snippets/code/tutorials/integrations/local-subsquid/hardhat-config.js
  .snippets/code/tutorials/integrations/local-subsquid/main-with-logging.ts
  .snippets/code/tutorials/integrations/local-subsquid/main.ts
  .snippets/code/tutorials/integrations/local-subsquid/processor.ts
  .snippets/code/tutorials/integrations/local-subsquid/sample-query.graphql
  .snippets/code/tutorials/integrations/local-subsquid/schema.graphql
  .snippets/code/tutorials/integrations/local-subsquid/transactions.js
  images/tutorials/integrations/local-subsquid/local-squid-2.png
  images/tutorials/integrations/local-subsquid/local-squid-3.png
  images/tutorials/integrations/local-subsquid/local-squid-4.png
  images/tutorials/integrations/local-subsquid/local-squid-5.png
  images/tutorials/integrations/local-subsquid/local-squid-6.png
  images/tutorials/integrations/local-subsquid/local-squid-7.png
  images/tutorials/integrations/local-subsquid/local-squid-8.png
  tutorials/integrations/local-subsquid.md
Labels: A1 - Maintenance Major

#787 add support for MBIP-5 on moonriver
  builders/get-started/eth-compare/tx-fees.md
  variables.yml
Labels: A2 - Maintenance Minor
