Repository moonbeam-foundation/moonbeam-docs, pull requests merged in 2024-04, with the labels that each got.

#898 Adding article for new relay data verifier precompile
  .snippets/code/builders/pallets-precompiles/precompiles/relay-data-verifier/RelayDataVerifier.sol
  .snippets/code/builders/pallets-precompiles/precompiles/relay-data-verifier/abi.js
  .snippets/code/builders/pallets-precompiles/precompiles/relay-data-verifier/ethers-relay-data-verifier.js
  .snippets/code/builders/pallets-precompiles/precompiles/relay-data-verifier/web3js-relay-data-verifier.js
  .snippets/code/builders/pallets-precompiles/precompiles/relay-data-verifier/web3py-relay-data-verifier.py
  .snippets/text/builders/pallets-precompiles/precompiles/relay-data-verifier/relay-data-verifier-parameters.md
  builders/pallets-precompiles/precompiles/.pages
  builders/pallets-precompiles/precompiles/relay-data-verifier.md
Labels: A0 - New Content

#907 add xcTNKR to list of xc-20s
  builders/interoperability/xcm/xc20/overview.md
Labels: A3 - Quick Fixes

#903 Add RPC Rate Limits and Re-Add OnFinality Endpoints
  .snippets/text/builders/get-started/endpoints/moonbase.md
  .snippets/text/builders/get-started/endpoints/moonbeam.md
  .snippets/text/builders/get-started/endpoints/moonriver.md
Labels: A2 - Maintenance Minor

#905 Update the alphanet relay chain endpoint
  .snippets/code/builders/interoperability/xcm/remote-execution/remote-evm-calls/send.js
  .snippets/code/builders/pallets-precompiles/precompiles/relay-data-verifier/ethers-relay-data-verifier.js
  .snippets/code/builders/pallets-precompiles/precompiles/relay-data-verifier/web3js-relay-data-verifier.js
  .snippets/code/builders/pallets-precompiles/precompiles/relay-data-verifier/web3py-relay-data-verifier.py
  .snippets/code/tutorials/interoperability/remote-batched-evm-calls/build-xcm-message.js
  .snippets/code/tutorials/interoperability/remote-batched-evm-calls/send-xcm-message.js
  .snippets/code/tutorials/interoperability/remote-staking/remote-staking.js
  .snippets/code/tutorials/interoperability/uniswapv2-swap/build-xcm-message.js
  .snippets/code/tutorials/interoperability/uniswapv2-swap/send-xcm-message.js
  .snippets/text/builders/get-started/endpoints/moonbase.md
  .snippets/text/builders/interoperability/xcm/calculate-multilocation-derivative-account.md
  builders/interoperability/xcm/remote-execution/remote-evm-calls.md
  builders/interoperability/xcm/xc-registration/xc-integration.md
  learn/platform/networks/overview.md
  tutorials/interoperability/remote-batched-evm-calls.md
  tutorials/interoperability/remote-staking-xcm.md
  tutorials/interoperability/uniswapv2-swap-xcm.md
Labels: A3 - Quick Fixes

#902 Update Hardhat Tutorials to Use Hardhat Ignition Modules
  .snippets/code/builders/build/eth-api/dev-env/hardhat/terminal/compile.md
  .snippets/code/builders/build/eth-api/dev-env/hardhat/terminal/deploy-moonbase.md
  .snippets/code/builders/build/eth-api/dev-env/hardhat/terminal/hardhat-create.md
  .snippets/code/builders/build/eth-api/dev-env/hardhat/terminal/interact.md
  .snippets/code/builders/build/eth-api/dev-env/hardhat/terminal/private-keys.md
  .snippets/code/builders/build/eth-api/dev-env/hardhat/terminal/run.md
  .snippets/code/tutorials/eth-api/hardhat-start-to-end/DelegationDAO.sol
  .snippets/code/tutorials/eth-api/hardhat-start-to-end/dao-js-test-file.js
  .snippets/code/tutorials/eth-api/hardhat-start-to-end/terminal/compile.md
  .snippets/code/tutorials/eth-api/hardhat-start-to-end/terminal/deploy-moonbase.md
  .snippets/code/tutorials/eth-api/hardhat-start-to-end/terminal/deploy-moonbeam.md
  .snippets/code/tutorials/eth-api/hardhat-start-to-end/terminal/hardhat-create.md
  .snippets/code/tutorials/eth-api/hardhat-start-to-end/terminal/test.md
  .snippets/code/tutorials/eth-api/hardhat-start-to-end/terminal/verify-moonbase.md
  .snippets/code/tutorials/eth-api/hardhat-start-to-end/terminal/verify-moonbeam.md
  builders/build/eth-api/dev-env/hardhat.md
  tutorials/eth-api/hardhat-start-to-end.md
  variables.yml
Labels: A1 - Maintenance Major

#909 bump cient to v0.37.0 and moonbase runtime to 2902
  builders/build/canonical-contracts.md
  builders/interoperability/xcm/core-concepts/weights-fees.md
  builders/interoperability/xcm/remote-execution/remote-evm-calls.md
  builders/pallets-precompiles/precompiles/overview.md
  variables.yml
Labels: A2 - Maintenance Minor

#910 minor update to the transact through sovereign function
  builders/interoperability/xcm/remote-execution/substrate-calls/xcm-transactor-pallet.md
Labels: A3 - Quick Fixes

#913 Update block gas limits
  builders/build/runtime-upgrades.md
  builders/interoperability/xcm/remote-execution/remote-evm-calls.md
  learn/platform/networks/moonbase.md
  variables.yml
Labels: A2 - Maintenance Minor

#915 Update conviction-voting.md
  builders/pallets-precompiles/precompiles/conviction-voting.md
Labels: A3 - Quick Fixes

#914 add xcSTINK to list of assets
  builders/interoperability/xcm/xc20/overview.md
Labels: A3 - Quick Fixes

#887 Adding eth_getBlockReceipts and Batch request to rpc-support.md
  builders/get-started/eth-compare/rpc-support.md
Labels: A3 - Quick Fixes
