Repository moonbeam-foundation/moonbeam-docs, pull requests merged in 2024-09, with the labels that each got.

#986 updates moonbeam.spec_version to runtime-3100
  builders/interoperability/xcm/core-concepts/weights-fees.md
  variables.yml
Labels: A2 - Maintenance Minor

#985 updates gas_block for moonbase from 15mln to 30mln for RT3100
  variables.yml
Labels: A2 - Maintenance Minor

#988 adds block for moonbeam rt3100
  builders/build/runtime-upgrades.md
Labels: A2 - Maintenance Minor

#989 Gas Limit Info on Networks Getting Started Page
  builders/get-started/networks/moonbase.md
  builders/get-started/networks/moonbeam.md
  builders/get-started/networks/moonriver.md
  learn/platform/networks/moonbeam.md
Labels: A2 - Maintenance Minor

#995 Dawn/updates version terminals
  .snippets/code/builders/ethereum/json-rpc/debug-trace/terminal/start-up-logs.md
  .snippets/code/builders/get-started/networks/moonbeam-dev/terminal/docker-pull.md
  .snippets/code/builders/get-started/networks/moonbeam-dev/terminal/docker-run.md
  .snippets/code/builders/get-started/networks/moonbeam-dev/terminal/sidecar.md
Labels: A3 - Quick Fixes

#990 Add Instructions for Creating and Removing Proxy via Apps.Moonbeam.Network
  images/tokens/manage/proxy-accounts/proxies-1.webp
  images/tokens/manage/proxy-accounts/proxies-10.webp
  images/tokens/manage/proxy-accounts/proxies-11.webp
  images/tokens/manage/proxy-accounts/proxies-12.webp
  images/tokens/manage/proxy-accounts/proxies-13.webp
  images/tokens/manage/proxy-accounts/proxies-14.webp
  images/tokens/manage/proxy-accounts/proxies-15.webp
  images/tokens/manage/proxy-accounts/proxies-2.webp
  images/tokens/manage/proxy-accounts/proxies-3.webp
  images/tokens/manage/proxy-accounts/proxies-4.webp
  images/tokens/manage/proxy-accounts/proxies-5.webp
  images/tokens/manage/proxy-accounts/proxies-6.webp
  images/tokens/manage/proxy-accounts/proxies-7.webp
  images/tokens/manage/proxy-accounts/proxies-8.webp
  tokens/manage/proxy-accounts.md
Labels: A1 - Maintenance Major

#992 Add Sidecar Custom Types Bundle Instructions
  builders/substrate/libraries/sidecar.md
Labels: A1 - Maintenance Major

#997 Update Gas Limit to 60M for Moonbeam
  variables.yml
Labels: A3 - Quick Fixes

#998 add runtime upgrade 3102 vars
  builders/build/runtime-upgrades.md
  variables.yml
Labels: A3 - Quick Fixes

#1000 Clarification on Transferable balances
  learn/core-concepts/balances.md
Labels: A2 - Maintenance Minor

#1002 Update Sidecar Version
  variables.yml
Labels: A3 - Quick Fixes
