Repository moonbeam-foundation/moonbeam-docs, pull requests merged in 2024-08, with the labels that each got.

#967 updates spec_version for moonbase, updates runtime upgrades by block …
  builders/build/runtime-upgrades.md
  builders/interoperability/xcm/core-concepts/weights-fees.md
  builders/interoperability/xcm/remote-execution/remote-evm-calls.md
  variables.yml
Labels: A2 - Maintenance Minor

#959 Update Subsquid to SQD Naming
  builders/integrations/indexers/.pages
  builders/integrations/indexers/subsquid.md
  tutorials/integrations/.pages
  tutorials/integrations/local-subsquid.md
  tutorials/integrations/nft-subsquid.md
Labels: A2 - Maintenance Minor

#962 Update Ethers js to modern docs standards
  .snippets/code/builders/ethereum/libraries/ethers-js/terminal/deploy.md
  .snippets/code/builders/ethereum/libraries/ethers-js/terminal/increment.md
  .snippets/code/builders/ethereum/libraries/ethers-js/terminal/reset.md
  .snippets/code/builders/ethereum/libraries/ethers-js/terminal/transaction.md
  builders/ethereum/libraries/ethersjs.md
  images/builders/ethereum/libraries/ethers/ethers-1.webp
  images/builders/ethereum/libraries/ethers/ethers-2.webp
  images/builders/ethereum/libraries/ethers/ethers-3.webp
  images/builders/ethereum/libraries/ethers/ethers-4.webp
Labels: A2 - Maintenance Minor

#963 Update Web3 Js to modern docs standards
  .snippets/code/builders/ethereum/libraries/web3-js/terminal/deploy.md
  .snippets/code/builders/ethereum/libraries/web3-js/terminal/increment.md
  .snippets/code/builders/ethereum/libraries/web3-js/terminal/reset.md
  .snippets/code/builders/ethereum/libraries/web3-js/terminal/transaction.md
  builders/ethereum/libraries/web3js.md
  images/builders/ethereum/libraries/web3js/web3js-1.webp
  images/builders/ethereum/libraries/web3js/web3js-2.webp
  images/builders/ethereum/libraries/web3js/web3js-3.webp
  images/builders/ethereum/libraries/web3js/web3js-4.webp
Labels: A2 - Maintenance Minor

#964 Modernize Ethers RS page
  .snippets/code/builders/ethereum/libraries/ethers-rust/terminal/deploy.md
  .snippets/code/builders/ethereum/libraries/ethers-rust/terminal/increment.md
  .snippets/code/builders/ethereum/libraries/ethers-rust/terminal/reset.md
  .snippets/code/builders/ethereum/libraries/ethers-rust/terminal/transaction.md
  builders/ethereum/libraries/ethersrs.md
  images/builders/ethereum/libraries/ethersrs/ethersrs-1.webp
  images/builders/ethereum/libraries/ethersrs/ethersrs-2.webp
  images/builders/ethereum/libraries/ethersrs/ethersrs-3.webp
  images/builders/ethereum/libraries/ethersrs/ethersrs-4.webp
Labels: A2 - Maintenance Minor

#965 Modernize Viem Page
  .snippets/code/builders/ethereum/libraries/viem/terminal/balances.md
  .snippets/code/builders/ethereum/libraries/viem/terminal/deploy.md
  .snippets/code/builders/ethereum/libraries/viem/terminal/get.md
  .snippets/code/builders/ethereum/libraries/viem/terminal/increment.md
  .snippets/code/builders/ethereum/libraries/viem/terminal/reset.md
  .snippets/code/builders/ethereum/libraries/viem/terminal/transaction.md
  builders/ethereum/libraries/viem.md
  images/builders/ethereum/libraries/viem/viem-1.webp
  images/builders/ethereum/libraries/viem/viem-2.webp
  images/builders/ethereum/libraries/viem/viem-3.webp
  images/builders/ethereum/libraries/viem/viem-4.webp
  images/builders/ethereum/libraries/viem/viem-5.webp
  images/builders/ethereum/libraries/viem/viem-6.webp
Labels: A2 - Maintenance Minor

#973 update links for tutorials section
  js/handleLanguageChange.js
Labels: A3 - Quick Fixes

#972 Modernize Graph Node Docs
  .snippets/code/node-operators/indexer-nodes/graph-node/terminal/docker-compose-up.md
  .snippets/code/node-operators/indexer-nodes/graph-node/terminal/output.md
  .snippets/code/node-operators/indexer-nodes/graph-node/terminal/setup.md
  images/node-operators/indexer-nodes/the-graph/the-graph-node-1.webp
  images/node-operators/indexer-nodes/the-graph/the-graph-node-2.webp
  images/node-operators/indexer-nodes/the-graph/the-graph-node-3.webp
  node-operators/indexer-nodes/thegraph-node.md
Labels: A2 - Maintenance Minor

#971 Modernize Web3py Docs
  .snippets/code/builders/ethereum/libraries/web3-py/terminal/deploy.md
  .snippets/code/builders/ethereum/libraries/web3-py/terminal/increment.md
  .snippets/code/builders/ethereum/libraries/web3-py/terminal/reset.md
  .snippets/code/builders/ethereum/libraries/web3-py/terminal/transaction.md
  builders/ethereum/libraries/web3py.md
  images/builders/ethereum/libraries/web3py/web3py-1.webp
  images/builders/ethereum/libraries/web3py/web3py-2.webp
  images/builders/ethereum/libraries/web3py/web3py-3.webp
  images/builders/ethereum/libraries/web3py/web3py-4.webp
Labels: A2 - Maintenance Minor

#975 Add info on session keys for node operators
  .snippets/text/node-operators/networks/run-a-node/systemd/run-service.md
  node-operators/networks/run-a-node/docker.md
  node-operators/networks/run-a-node/systemd.md
Labels: A1 - Maintenance Major

#968 Update Remote XCM Tutorials
  .snippets/code/tutorials/interoperability/remote-batched-evm-calls/terminal/calculate.md
  .snippets/code/tutorials/interoperability/remote-staking/terminal/calculate.md
  .snippets/code/tutorials/interoperability/uniswapv2-swap/terminal/calculate.md
Labels: A2 - Maintenance Minor

#974 adds moon_getLatestSyncedBlock to moonbeam custom API methods
  builders/ethereum/json-rpc/moonbeam-custom-api.md
Labels: A2 - Maintenance Minor

#942 Revamp ThirdWeb Docs
  .snippets/code/builders/ethereum/dev-env/thirdweb/initialize.ts
  .snippets/code/tutorials/eth-api/thirdweb/chains.ts
  .snippets/code/tutorials/eth-api/thirdweb/marketplace-contracts.ts
  .snippets/code/tutorials/eth-api/thirdweb/nft-contracts.ts
  builders/ethereum/dev-env/thirdweb.md
  images/builders/ethereum/dev-env/thirdweb/thirdweb-2.webp
  images/builders/ethereum/dev-env/thirdweb/thirdweb-3.webp
  images/builders/ethereum/dev-env/thirdweb/thirdweb-4.webp
  images/tutorials/eth-api/thirdweb/thirdweb-1.webp
  images/tutorials/eth-api/thirdweb/thirdweb-2.webp
  images/tutorials/eth-api/thirdweb/thirdweb-3.webp
  images/tutorials/eth-api/thirdweb/thirdweb-4.webp
  images/tutorials/eth-api/thirdweb/thirdweb-5.webp
  images/tutorials/eth-api/thirdweb/thirdweb-6.webp
  images/tutorials/eth-api/thirdweb/thirdweb-7.webp
  tutorials/eth-api/.pages
  tutorials/eth-api/thirdweb.md
Labels: A1 - Maintenance Major

#970 Modernize Wormhole Docs
  .snippets/code/builders/interoperability/protocols/wormhole/terminal/run-start.md
  .snippets/code/builders/interoperability/protocols/wormhole/terminal/send.md
  .snippets/code/builders/interoperability/protocols/wormhole/terminal/setup-spy.md
  builders/interoperability/protocols/wormhole.md
  images/builders/interoperability/protocols/wormhole/wormhole-3.webp
  images/builders/interoperability/protocols/wormhole/wormhole-4.webp
  images/builders/interoperability/protocols/wormhole/wormhole-5.webp
  images/builders/interoperability/protocols/wormhole/wormhole-6.webp
  images/builders/interoperability/protocols/wormhole/wormhole-7.webp
  images/builders/interoperability/protocols/wormhole/wormhole-8.webp
  images/builders/interoperability/protocols/wormhole/wormhole-9.webp
Labels: A2 - Maintenance Minor

#969 Adds MBF DApp Directory API Documentation
  .snippets/code/learn/dapps-list/dapp-directory/categories.md
  .snippets/code/learn/dapps-list/dapp-directory/nfts.json
  .snippets/code/learn/dapps-list/dapp-directory/project-data-file.json
  .snippets/code/learn/dapps-list/dapp-directory/stellaswap.json
  .snippets/code/learn/dapps-list/dapp-directory/tags.md
  learn/dapps-list/dapp-directory.md
Labels: A2 - Maintenance Minor

#976 update X-Tokens precompile interface docs for consistency
  builders/interoperability/xcm/xc20/send-xc20s/xtokens-precompile.md
Labels: A3 - Quick Fixes

#977 Bump polkadot-sdk to v1.11.0
  builders/interoperability/xcm/core-concepts/multilocations.md
  builders/interoperability/xcm/core-concepts/weights-fees.md
  builders/interoperability/xcm/remote-execution/computed-origins.md
  builders/interoperability/xcm/remote-execution/substrate-calls/xcm-transactor-pallet.md
  builders/interoperability/xcm/xc20/send-xc20s/overview.md
  variables.yml
Labels: A2 - Maintenance Minor

#956 Adds RainbowKit to Integrations > Wallets
  .DS_Store
  .snippets/code/builders/integrations/wallets/rainbowkit/layout.tsx
  .snippets/code/builders/integrations/wallets/rainbowkit/page.tsx
  .snippets/code/builders/integrations/wallets/rainbowkit/plainProviders.tsx
  .snippets/code/builders/integrations/wallets/rainbowkit/providers.tsx
  .snippets/code/builders/integrations/wallets/rainbowkit/terminal/cli-quickstart.md
  .snippets/code/builders/integrations/wallets/rainbowkit/wagmi.ts
  builders/.DS_Store
  builders/integrations/.DS_Store
  builders/integrations/wallets/.DS_Store
  builders/integrations/wallets/.pages
  builders/integrations/wallets/rainbowkit.md
  images/builders/integrations/wallets/.DS_Store
  images/builders/integrations/wallets/rainbowkit/rainbowkit-1.webp
  images/builders/integrations/wallets/rainbowkit/rainbowkit-2.webp
  images/builders/integrations/wallets/rainbowkit/rainbowkit-3.webp
Labels: A0 - New Content

#981 Fixed node key generation issues
  node-operators/networks/run-a-node/docker.md
  node-operators/networks/run-a-node/systemd.md
Labels: A3 - Quick Fixes

#966 Adding pallet xcm interface precompile
  .snippets/code/builders/interoperability/xcm/xc20/send-xc20s/eth-api/XcmInterface.sol
  builders/ethereum/precompiles/interoperability/.pages
  builders/ethereum/precompiles/overview.md
  builders/interoperability/xcm/xc20/send-xc20s/.pages
  builders/interoperability/xcm/xc20/send-xc20s/eth-api.md
  images/builders/interoperability/xcm/xc20/send-xc20s/eth-api/eth-api-1.webp
  images/builders/interoperability/xcm/xc20/send-xc20s/eth-api/eth-api-2.webp
  images/builders/interoperability/xcm/xc20/send-xc20s/eth-api/eth-api-3.webp
  images/builders/interoperability/xcm/xc20/send-xc20s/eth-api/eth-api-4.webp
  images/builders/interoperability/xcm/xc20/send-xc20s/eth-api/eth-api-5.webp
  images/builders/interoperability/xcm/xc20/send-xc20s/eth-api/eth-api-6.webp
  variables.yml
Labels: A0 - New Content

#980 updates moonriver 3100 runtime
  builders/build/runtime-upgrades.md
  builders/interoperability/xcm/core-concepts/weights-fees.md
  variables.yml
Labels: A2 - Maintenance Minor

#982 update the sha256sum for moonriver and moonbeam
  variables.yml
Labels: A3 - Quick Fixes

#951 Add article for moralis
  builders/integrations/indexers/.pages
  builders/integrations/indexers/moralis.md
  images/builders/integrations/indexers/moralis/moralis-1.webp
  images/builders/integrations/indexers/moralis/moralis-2.webp
  images/builders/integrations/indexers/moralis/moralis-3.webp
  images/builders/integrations/indexers/moralis/moralis-4.webp
  images/builders/integrations/indexers/moralis/moralis-5.webp
  images/builders/integrations/indexers/moralis/moralis-6.webp
  images/builders/integrations/indexers/moralis/moralis-7.webp
Labels: A0 - New Content

#983 temporary fix for the images
  builders/integrations/indexers/moralis.md
  images/builders/integrations/indexers/moralis/moralis-5.webp
  images/builders/integrations/indexers/moralis/moralis-6.webp
Labels: A3 - Quick Fixes

#984 Add missing image for Moralis doc
  builders/integrations/indexers/moralis.md
  images/builders/integrations/indexers/moralis/moralis-5.webp
Labels: A3 - Quick Fixes
