Repository moonbeam-foundation/moonbeam-docs, pull requests merged in 2024-01, with the labels that each got.

#825 bump to ubuntu 22.04
  .snippets/code/builders/build/eth-api/pubsub/subscribe-to-event-logs.js
  .snippets/code/builders/build/eth-api/pubsub/use-wildcards.js
  .snippets/text/_common/assumes-mac-or-ubuntu-env.md
  builders/build/eth-api/libraries/web3py.md
  builders/build/eth-api/pubsub.md
  builders/get-started/networks/moonbeam-dev.md
  node-operators/networks/run-a-node/compile-binary.md
Labels: A2 - Maintenance Minor

#829 add composable assets
  builders/interoperability/xcm/xc20/overview.md
Labels: A2 - Maintenance Minor

#833 bump polkadot sdk version to v1.3.0
  builders/interoperability/xcm/core-concepts/weights-fees.md
  builders/interoperability/xcm/remote-execution/computed-origins.md
  builders/interoperability/xcm/remote-execution/substrate-calls/xcm-transactor-pallet.md
  variables.yml
Labels: A2 - Maintenance Minor

#832 bump to client v0.35.0
  variables.yml
Labels: A2 - Maintenance Minor

#839 add xcpink
  builders/interoperability/xcm/xc20/overview.md
Labels: A3 - Quick Fixes

#834 update subsquid archive urls
  builders/integrations/indexers/subsquid.md
Labels: A3 - Quick Fixes

#838 update wording on calculating eip-1559 transaction fees
  .snippets/code/builders/get-started/eth-compare/tx-fees/tx-fees-block-dynamic.js
  builders/get-started/eth-compare/tx-fees.md
Labels: A3 - Quick Fixes

#830 Update usage of the balances pallet
  .snippets/code/builders/build/substrate-api/polkadot-js-api/basic-transactions.js
  .snippets/code/builders/build/substrate-api/polkadot-js-api/batch-transactions.js
  .snippets/code/builders/build/substrate-api/polkadot-js-api/payment-info.js
  .snippets/code/builders/get-started/eth-compare/transfers-api/sidecar-transfer.js
  builders/build/substrate-api/polkadot-js-api.md
  builders/get-started/eth-compare/transfers-api.md
Labels: A2 - Maintenance Minor

#837 Update the moonbase spec version to runtime 2700
  builders/build/runtime-upgrades.md
  builders/interoperability/xcm/core-concepts/weights-fees.md
  builders/interoperability/xcm/remote-execution/remote-evm-calls.md
  variables.yml
Labels: A2 - Maintenance Minor

#842 Add termynal
  .snippets/code/builders/get-started/networks/moonbeam-dev/terminal/compile.md
  .snippets/code/builders/get-started/networks/moonbeam-dev/terminal/docker-pull.md
  .snippets/code/builders/get-started/networks/moonbeam-dev/terminal/docker-run.md
  .snippets/code/builders/get-started/networks/moonbeam-dev/terminal/run-binary.md
  builders/get-started/networks/moonbeam-dev.md
  js/termynal.min.js
Labels: A2 - Maintenance Minor

#843 Py Substrate Interface - Minor fix in script
  builders/build/substrate-api/py-substrate-interface.md
Labels: A3 - Quick Fixes

#831 update to polkadot runtime v1.0.1 and alphanet runtime v1.2.0
  builders/interoperability/xcm/core-concepts/weights-fees.md
  builders/interoperability/xcm/xc20/send-xc20s/overview.md
  builders/interoperability/xcm/xc20/send-xc20s/xtokens-pallet.md
  builders/interoperability/xcm/xc20/send-xc20s/xtokens-precompile.md
  variables.yml
Labels: A2 - Maintenance Minor

#848 update mrl repo github link example
  builders/interoperability/mrl.md
Labels: A3 - Quick Fixes

#846 update termynal snippets
  .snippets/code/builders/get-started/networks/moonbeam-dev/terminal/docker-pull.md
  .snippets/code/builders/get-started/networks/moonbeam-dev/terminal/docker-run.md
  .snippets/code/builders/get-started/networks/moonbeam-dev/terminal/run-binary.md
Labels: A3 - Quick Fixes

#849 update xcm transactor for the overall weight changes
  .snippets/code/builders/interoperability/xcm/remote-execution/substrate-calls/xcm-transactor-pallet/interface-examples/hrmp-manage.js
  .snippets/code/builders/interoperability/xcm/remote-execution/substrate-calls/xcm-transactor-pallet/interface-examples/transact-through-signed.js
  .snippets/code/builders/interoperability/xcm/remote-execution/substrate-calls/xcm-transactor-pallet/interface-examples/transact-through-sovereign.js
  .snippets/code/builders/interoperability/xcm/remote-execution/substrate-calls/xcm-transactor-pallet/transact-signed.js
  .snippets/code/builders/interoperability/xcm/remote-execution/substrate-calls/xcm-transactor-precompile/XcmTransactorV3.sol
  builders/interoperability/xcm/remote-execution/substrate-calls/xcm-transactor-pallet.md
  builders/interoperability/xcm/remote-execution/substrate-calls/xcm-transactor-precompile.md
Labels: A2 - Maintenance Minor

#844 remove local dev node images
  images/builders/get-started/networks/moonbeam-dev/moonbeam-dev-1.png
  images/builders/get-started/networks/moonbeam-dev/moonbeam-dev-2.png
  images/builders/get-started/networks/moonbeam-dev/moonbeam-dev-3.png
  images/builders/get-started/networks/moonbeam-dev/moonbeam-dev-4.png
  images/builders/get-started/networks/moonbeam-dev/moonbeam-dev-5.png
  images/builders/get-started/networks/moonbeam-dev/moonbeam-dev-6.png
  images/builders/get-started/networks/moonbeam-dev/moonbeam-dev-7.png
Labels: A3 - Quick Fixes

#840 Brownie updates
  .snippets/code/builders/build/eth-api/dev-env/brownie/terminal/compile.md
  .snippets/code/builders/build/eth-api/dev-env/brownie/terminal/deploy.md
  .snippets/code/builders/build/eth-api/dev-env/brownie/terminal/init.md
  .snippets/code/builders/build/eth-api/dev-env/brownie/terminal/interact.md
  .snippets/code/builders/build/eth-api/dev-env/brownie/terminal/list-networks.md
  .snippets/code/builders/build/eth-api/dev-env/brownie/terminal/modify-networks.md
  .snippets/code/builders/build/eth-api/dev-env/brownie/terminal/new-account.md
  builders/build/eth-api/dev-env/brownie.md
  images/builders/build/eth-api/dev-env/brownie/brownie-1.png
  images/builders/build/eth-api/dev-env/brownie/brownie-2.png
  images/builders/build/eth-api/dev-env/brownie/brownie-3.png
  images/builders/build/eth-api/dev-env/brownie/brownie-4.png
  images/builders/build/eth-api/dev-env/brownie/brownie-5.png
  images/builders/build/eth-api/dev-env/brownie/brownie-6.png
Labels: A2 - Maintenance Minor

#841 add a section on marking collators as inactive
  images/node-operators/networks/collators/activities/activities-12.png
  node-operators/networks/collators/activities.md
  variables.yml
Labels: A1 - Maintenance Major

#847 Add Foundry Scripting Section
  .snippets/code/builders/build/eth-api/dev-env/foundry/MyToken-script.sol
  .snippets/code/builders/build/eth-api/dev-env/foundry/terminal/burn.md
  .snippets/code/builders/build/eth-api/dev-env/foundry/terminal/cast.md
  .snippets/code/builders/build/eth-api/dev-env/foundry/terminal/compile.md
  .snippets/code/builders/build/eth-api/dev-env/foundry/terminal/deploy.md
  .snippets/code/builders/build/eth-api/dev-env/foundry/terminal/expression.md
  .snippets/code/builders/build/eth-api/dev-env/foundry/terminal/fork-anvil.md
  .snippets/code/builders/build/eth-api/dev-env/foundry/terminal/memdump.md
  .snippets/code/builders/build/eth-api/dev-env/foundry/terminal/query-balance.md
  .snippets/code/builders/build/eth-api/dev-env/foundry/terminal/rawstack.md
  .snippets/code/builders/build/eth-api/dev-env/foundry/terminal/save-state.md
  .snippets/code/builders/build/eth-api/dev-env/foundry/terminal/script.md
  builders/build/eth-api/dev-env/foundry.md
Labels: A1 - Maintenance Major

#853 add grammarly to checklist
  .github/pull-request-template.md
Labels: A3 - Quick Fixes

#854 New XCM-SDK Links
  builders/build/historical-updates.md
  builders/interoperability/xcm/xcm-sdk/v0/xcm-sdk.md
  builders/interoperability/xcm/xcm-sdk/v1/xcm-sdk.md
  node-operators/networks/run-a-node/overview.md
Labels: A3 - Quick Fixes

#857 Polkadot API Get Balances Fix
  .snippets/code/builders/get-started/eth-compare/balances/balance.js
Labels: A3 - Quick Fixes

#858 update moonriver to rt 2700
  builders/build/runtime-upgrades.md
  builders/interoperability/xcm/core-concepts/weights-fees.md
  variables.yml
Labels: A3 - Quick Fixes

#835 Identity Precompile available on Moonbeam and Moonriver
  builders/build/canonical-contracts.md
  builders/pallets-precompiles/precompiles/identity.md
  builders/pallets-precompiles/precompiles/overview.md
Labels: A2 - Maintenance Minor
