Repository moonbeam-foundation/moonbeam-docs, pull requests merged in 2024-05, with the labels that each got.

#916 add the storage cleaner precompile
  .snippets/text/builders/build/canonical-contracts/eth-mainnet.md
  .snippets/text/builders/build/canonical-contracts/non-specific.md
Labels: A3 - Quick Fixes

#921 bump moonriver to runtime 2901
  builders/build/canonical-contracts.md
  builders/build/runtime-upgrades.md
  builders/interoperability/xcm/core-concepts/weights-fees.md
  builders/pallets-precompiles/precompiles/overview.md
  variables.yml
Labels: A3 - Quick Fixes

#895 Add Docs on GMP vs XCM
  images/learn/features/xchain-plans/xchain-plans-1.webp
  images/learn/features/xchain-plans/xchain-plans-2.webp
  learn/features/.pages
  learn/features/xchain-plans.md
Labels: A1 - Maintenance Major

#917 add support for the fast general admin track on moonbeam and moonriver
  learn/features/governance.md
  variables.yml
Labels: A2 - Maintenance Minor

#919 Update Sidecar version to 18.0.0
  .snippets/code/builders/get-started/networks/moonbeam-dev/terminal/sidecar.md
  builders/build/substrate-api/sidecar.md
  images/builders/build/substrate-api/sidecar/sidecar-1.webp
  variables.yml
Labels: A3 - Quick Fixes

#924 Remove image for foundry tutorial
  images/builders/build/eth-api/dev-env/foundry/foundry-1.webp
  images/builders/build/eth-api/dev-env/foundry/foundry-10.webp
  images/builders/build/eth-api/dev-env/foundry/foundry-2.webp
  images/builders/build/eth-api/dev-env/foundry/foundry-3.webp
  images/builders/build/eth-api/dev-env/foundry/foundry-4.webp
  images/builders/build/eth-api/dev-env/foundry/foundry-5.webp
  images/builders/build/eth-api/dev-env/foundry/foundry-6.webp
  images/builders/build/eth-api/dev-env/foundry/foundry-7.webp
  images/builders/build/eth-api/dev-env/foundry/foundry-8.webp
  images/builders/build/eth-api/dev-env/foundry/foundry-9.webp
Labels: A3 - Quick Fixes

#925 fix 404s
  builders/build/eth-api/libraries/ethersjs.md
  builders/build/eth-api/libraries/viem.md
  builders/get-started/quick-start.md
  builders/integrations/gaming/metafab.md
  builders/integrations/indexers/covalent.md
  builders/integrations/indexers/subquery.md
  builders/integrations/oracles/api3.md
  builders/interoperability/xcm/xcm-sdk/v1/xcm-sdk.md
  learn/platform/networks/moonriver.md
  node-operators/networks/collators/faq.md
  tokens/staking/stake.md
  tutorials/eth-api/batch-approve-swap.md
  tutorials/integrations/nft-subsquid.md
Labels: A2 - Maintenance Minor

#926 update the index nft transfers docs
  .snippets/code/tutorials/integrations/nft-subsquid/contract.ts
  .snippets/code/tutorials/integrations/nft-subsquid/main.ts
  .snippets/code/tutorials/integrations/nft-subsquid/processor.ts
  .snippets/code/tutorials/integrations/nft-subsquid/schema.graphql
  tutorials/integrations/nft-subsquid.md
Labels: A1 - Maintenance Major

#927 bump moonbeam to 2901
  builders/build/canonical-contracts.md
  builders/build/runtime-upgrades.md
  builders/interoperability/xcm/core-concepts/weights-fees.md
  builders/pallets-precompiles/precompiles/overview.md
  variables.yml
Labels: A3 - Quick Fixes

#932 update build script
  .github/workflows/check-mkdocs-build.yml
Labels: A2 - Maintenance Minor

#931 Update eth-rpc.md
  builders/json-rpc/eth-rpc.md
Labels: A2 - Maintenance Minor

#933 update to v0.38.0
  .snippets/code/builders/get-started/networks/moonbeam-dev/terminal/docker-pull.md
  .snippets/code/builders/get-started/networks/moonbeam-dev/terminal/docker-run.md
  .snippets/code/builders/get-started/networks/moonbeam-dev/terminal/run-binary.md
  .snippets/code/builders/get-started/networks/moonbeam-dev/terminal/sidecar.md
  .snippets/code/builders/json-rpc/debug-trace/terminal/start-up-logs.md
  variables.yml
Labels: A3 - Quick Fixes
