Repository moonbeam-foundation/moonbeam-docs, pull requests merged in 2024-07, with the labels that each got.

#948 Remove POKT network public endpoint info
  .snippets/text/builders/get-started/endpoints/moonbeam.md
  .snippets/text/builders/get-started/endpoints/moonriver.md
  builders/get-started/quick-start.md
Labels: A3 - Quick Fixes

#949 update broken images
  builders/ethereum/precompiles/features/governance/preimage.md
Labels: A3 - Quick Fixes

#953 update moonbeam for runtime 3001 and async backing
  builders/interoperability/xcm/core-concepts/weights-fees.md
  learn/platform/networks/moonbeam.md
  variables.yml
Labels: A2 - Maintenance Minor

#954 add moonbeam 3001 to runtime upgrades by block page
  builders/build/runtime-upgrades.md
Labels: A2 - Maintenance Minor

#955 Adds debug trace call
  builders/ethereum/json-rpc/debug-trace.md
  node-operators/networks/tracing-node.md
Labels: A2 - Maintenance Minor

#946 Update the API3 docs
  builders/integrations/oracles/api3.md
  images/builders/integrations/oracles/api3/api3-3.webp
  images/builders/integrations/oracles/api3/api3-4.webp
  images/builders/integrations/oracles/api3/api3-5.webp
  images/builders/integrations/oracles/api3/api3-6.webp
  images/builders/integrations/oracles/api3/api3-7.webp
  images/builders/integrations/oracles/api3/api3-8.webp
  variables.yml
Labels: A1 - Maintenance Major

#957 Update Axelar Cross-Chain NFT Mint Tutorial
  .snippets/code/tutorials/interoperability/axelar-sdk/terminal/status.md
  images/tutorials/interoperability/axelar-sdk/axelar-3.webp
  tutorials/interoperability/using-axelar-sdk.md
Labels: A2 - Maintenance Minor

#952 updates json rpcs
  builders/ethereum/json-rpc/eth-rpc.md
Labels: A1 - Maintenance Major

#958 Dawn/eth call state override
  builders/ethereum/json-rpc/eth-rpc.md
Labels: A2 - Maintenance Minor

#961 Fix Open Zeppelin Broken Link
  builders/ethereum/dev-env/openzeppelin/defender.md
Labels: A3 - Quick Fixes

#960 Dawn/bump to client v0.39.0
  .snippets/code/builders/ethereum/json-rpc/debug-trace/terminal/start-up-logs.md
  .snippets/code/builders/get-started/networks/moonbeam-dev/terminal/docker-pull.md
  .snippets/code/builders/get-started/networks/moonbeam-dev/terminal/docker-run.md
  .snippets/code/builders/get-started/networks/moonbeam-dev/terminal/run-binary.md
  .snippets/code/builders/get-started/networks/moonbeam-dev/terminal/sidecar.md
  variables.yml
Labels: A2 - Maintenance Minor
