Repository moonbeam-foundation/moonbeam-docs, pull requests merged in 2024-02, with the labels that each got.

#861 Frontier Link Updates
  .snippets/text/builders/build/canonical-contracts/eth-mainnet.md
  .snippets/text/builders/build/canonical-contracts/non-specific.md
  builders/build/eth-api/pubsub.md
  builders/build/historical-updates.md
  builders/build/substrate-api/overview.md
  builders/get-started/networks/moonbeam-dev.md
  builders/pallets-precompiles/precompiles/overview.md
  learn/features/eth-compatibility.md
Labels: A2 - Maintenance Minor

#859 Refresh Hyperlane Docs
  builders/interoperability/protocols/hyperlane.md
Labels: A2 - Maintenance Minor

#860 Refresh Wormhole Links
  builders/interoperability/protocols/wormhole.md
  builders/pallets-precompiles/precompiles/gmp.md
  tutorials/interoperability/cross-chain-dao.md
Labels: A2 - Maintenance Minor

#863 resize moonbot image
  images/moonbot.webp
Labels: A3 - Quick Fixes

#866 add xcvASTR and xcvMANTA
  builders/interoperability/xcm/xc20/overview.md
Labels: A2 - Maintenance Minor

#865 add deprecation notice to brownie
  builders/build/eth-api/dev-env/brownie.md
Labels: A3 - Quick Fixes

#868 Bump Moonbeam to Runtime 2700
  builders/build/runtime-upgrades.md
  builders/interoperability/xcm/core-concepts/weights-fees.md
  builders/interoperability/xcm/xc20/overview.md
  variables.yml
Labels: A2 - Maintenance Minor

#836 mbip-5 available on moonbeam
  builders/get-started/eth-compare/tx-fees.md
  variables.yml
Labels: A2 - Maintenance Minor

#862 remove the init kapa file
  js/initKapaWidget.js
Labels: A3 - Quick Fixes

#869 xcm sdk update: uses chain decimals
  builders/interoperability/xcm/xcm-sdk/v1/reference.md
  builders/interoperability/xcm/xcm-sdk/v1/xcm-sdk.md
Labels: A2 - Maintenance Minor

#870 Fix Chainlink Aggregator Contract Link
  builders/integrations/oracles/chainlink.md
Labels: A3 - Quick Fixes

#874 remove downtown moonbeam
  images/learn/dapps-list/dtmb/dtmb-1.webp
  images/learn/dapps-list/dtmb/dtmb-2.webp
  learn/dapps-list/.pages
  learn/dapps-list/dtmb.md
Labels: A2 - Maintenance Minor

#872 Add Coinbase Wallet Subscribe Docs
  images/tokens/connect/coinbase-wallet/coinbase-10.webp
  images/tokens/connect/coinbase-wallet/coinbase-11.webp
  images/tokens/connect/coinbase-wallet/coinbase-12.webp
  images/tokens/connect/coinbase-wallet/coinbase-13.webp
  images/tokens/connect/coinbase-wallet/coinbase-14.webp
  images/tokens/connect/coinbase-wallet/coinbase-8.webp
  images/tokens/connect/coinbase-wallet/coinbase-9.webp
  tokens/connect/coinbase-wallet.md
Labels: A0 - New Content

#876 Bump to client v0.36.0
  .snippets/code/builders/get-started/networks/moonbeam-dev/terminal/docker-pull.md
  .snippets/code/builders/get-started/networks/moonbeam-dev/terminal/docker-run.md
  variables.yml
Labels: A2 - Maintenance Minor

#871 Refresh and Migrate Axelar SDK Connected Contracts BlogPost to Docs Site
  .snippets/code/tutorials/interoperability/axelar-sdk/CrossChainNFT.sol
  .snippets/code/tutorials/interoperability/axelar-sdk/executeWithToken.sol
  .snippets/code/tutorials/interoperability/axelar-sdk/mint-1.js
  .snippets/code/tutorials/interoperability/axelar-sdk/mint-2.js
  .snippets/code/tutorials/interoperability/axelar-sdk/mint-3.js
  .snippets/code/tutorials/interoperability/axelar-sdk/mint-4.js
  .snippets/code/tutorials/interoperability/axelar-sdk/mint-5.js
  .snippets/code/tutorials/interoperability/axelar-sdk/mint-6.js
  .snippets/code/tutorials/interoperability/axelar-sdk/mintXCNFT.sol
  .snippets/code/tutorials/interoperability/axelar-sdk/query.js
  .snippets/code/tutorials/interoperability/axelar-sdk/terminal/deploy.md
  .snippets/code/tutorials/interoperability/axelar-sdk/terminal/mint.md
  images/tutorials/interoperability/axelar-sdk/axelar-1.webp
  images/tutorials/interoperability/axelar-sdk/axelar-2.webp
  images/tutorials/interoperability/axelar-sdk/axelar-3.webp
  tutorials/interoperability/.pages
  tutorials/interoperability/using-axelar-sdk.md
Labels: A0 - New Content
