Repository moonbeam-foundation/moonbeam-docs, pull requests merged in 2024-12, with the labels that each got.

#1032 chore: remove redundant words and fix some typos in comment
  builders/ethereum/precompiles/features/governance/preimage.md
  builders/integrations/wallets/rainbowkit.md
  learn/features/governance.md
  learn/features/staking.md
  learn/features/treasury.md
  tokens/manage/identity.md
Labels: A2 - Maintenance Minor

#1034 Parachain Bond Reserve Event Renaming
  builders/build/historical-updates.md
Labels: A2 - Maintenance Minor

#1033 Changed the SSD suggestions for running a node on all 3 networks
  variables.yml
Labels: A3 - Quick Fixes

#1035 Update Sidecar Version
  variables.yml
Labels: A3 - Quick Fixes

#1007 Overhaul Covalent (Goldrush) Docs
  .snippets/code/builders/integrations/indexers/covalent/all-txns-by-block-hash/request.sh
  .snippets/code/builders/integrations/indexers/covalent/all-txns-by-block-hash/response.sh
  .snippets/code/builders/integrations/indexers/covalent/cross-chain/request.sh
  .snippets/code/builders/integrations/indexers/covalent/cross-chain/response.sh
  .snippets/code/builders/integrations/indexers/covalent/earliest-transactions/request.sh
  .snippets/code/builders/integrations/indexers/covalent/earliest-transactions/response.sh
  .snippets/code/builders/integrations/indexers/covalent/erc20-approvals/request.sh
  .snippets/code/builders/integrations/indexers/covalent/erc20-approvals/response.sh
  .snippets/code/builders/integrations/indexers/covalent/get-a-transaction/request.sh
  .snippets/code/builders/integrations/indexers/covalent/get-a-transaction/response.sh
  .snippets/code/builders/integrations/indexers/covalent/get-all-txns-in-block/request.sh
  .snippets/code/builders/integrations/indexers/covalent/get-all-txns-in-block/response.sh
  .snippets/code/builders/integrations/indexers/covalent/get-bulk-time/request.sh
  .snippets/code/builders/integrations/indexers/covalent/get-bulk-time/response.sh
  .snippets/code/builders/integrations/indexers/covalent/get-erc20-transfers/request.sh
  .snippets/code/builders/integrations/indexers/covalent/get-erc20-transfers/response.sh
  .snippets/code/builders/integrations/indexers/covalent/get-paginated-transactions/request.sh
  .snippets/code/builders/integrations/indexers/covalent/get-paginated-transactions/response.sh
  .snippets/code/builders/integrations/indexers/covalent/javascript-using-async.js
  .snippets/code/builders/integrations/indexers/covalent/javascript-using-fetch.js
  .snippets/code/builders/integrations/indexers/covalent/native-token-balances/request.sh
  .snippets/code/builders/integrations/indexers/covalent/native-token-balances/response.sh
  .snippets/code/builders/integrations/indexers/covalent/nft-approvals/request.sh
  .snippets/code/builders/integrations/indexers/covalent/nft-approvals/response.sh
  .snippets/code/builders/integrations/indexers/covalent/python-example.py
  .snippets/code/builders/integrations/indexers/covalent/recent-transactions/request.sh
  .snippets/code/builders/integrations/indexers/covalent/recent-transactions/response.sh
  .snippets/code/builders/integrations/indexers/covalent/token-balances/request.sh
  .snippets/code/builders/integrations/indexers/covalent/token-balances/response.sh
  .snippets/code/builders/integrations/indexers/covalent/transaction-summary/request.sh
  .snippets/code/builders/integrations/indexers/covalent/transaction-summary/response.sh
  builders/integrations/indexers/.pages
  builders/integrations/indexers/covalent.md
  images/builders/integrations/indexers/covalent/covalent-1.webp
Labels: A1 - Maintenance Major

#1038 Add the Graph Moonbuilders Workshop to Graph Page
  builders/integrations/indexers/thegraph.md
Labels: A3 - Quick Fixes

#1036 New min gas gwei for Moonbase Alpha
  .snippets/code/tutorials/eth-api/foundry-start-to-end/terminal/deploy.md
  learn/core-concepts/tx-fees.md
  variables.yml
Labels: A3 - Quick Fixes

#1039 Runtime-Upgrade-MBA-3400
  builders/build/runtime-upgrades.md
  variables.yml
Labels: A3 - Quick Fixes

#1042 fix: typos in documentation files
  .CONTRIBUTING.md
Labels: A3 - Quick Fixes

#1045 chore: fix 404 status URL
  .CONTRIBUTING.md
Labels: A3 - Quick Fixes

#1049 Typos
  .snippets/code/builders/ethereum/json-rpc/pubsub/subscribe-to-event-logs.js
  .snippets/code/builders/ethereum/json-rpc/pubsub/use-wildcards.js
  .snippets/code/builders/ethereum/precompiles/account/identity/Identity.sol
  .snippets/code/builders/ethereum/precompiles/features/staking/StakingInterface.sol
  .snippets/code/builders/ethereum/precompiles/ux/batch/Batch.sol
  .snippets/code/builders/interoperability/xcm/remote-execution/substrate-calls/xcm-transactor-precompile/XcmTransactorV1.sol
  .snippets/code/builders/interoperability/xcm/remote-execution/substrate-calls/xcm-transactor-precompile/XcmTransactorV2.sol
  .snippets/code/builders/interoperability/xcm/remote-execution/substrate-calls/xcm-transactor-precompile/XcmTransactorV3.sol
  builders/ethereum/precompiles/features/governance/conviction-voting.md
  node-operators/oracle-nodes/node-chainlink.md
Labels: A3 - Quick Fixes

#1052 Typo
  node-operators/networks/collators/orbiter.md
Labels: A3 - Quick Fixes

#1029 Document Lazy Loading
  .snippets/code/node-operators/networks/run-a-node/terminal/lazy-loading.md
  builders/get-started/endpoints.md
  node-operators/networks/run-a-node/flags.md
  node-operators/networks/run-a-node/overview.md
Labels: A1 - Maintenance Major
