Repository moonbeam-foundation/moonbeam-docs, pull requests merged in 2024-06, with the labels that each got.

#929 add latest bugs and migrations
  builders/build/historical-updates.md
Labels: A2 - Maintenance Minor

#936 fix formatting on ethereum json rpc page
  builders/json-rpc/eth-rpc.md
Labels: A3 - Quick Fixes

#937 Update Etherscan Verification New PR
  .snippets/code/builders/build/eth-api/verify-contracts/etherscan-plugins/terminal/forge-create-verify.md
  .snippets/code/builders/build/eth-api/verify-contracts/etherscan-plugins/terminal/forge-verify.md
  .snippets/code/builders/build/eth-api/verify-contracts/etherscan-plugins/terminal/hardhat-verify.md
  builders/build/eth-api/verify-contracts/etherscan-plugins.md
  images/builders/build/eth-api/verify-contracts/etherscan-plugins/plugins-3.webp
  images/builders/build/eth-api/verify-contracts/etherscan-plugins/plugins-4.webp
  images/builders/build/eth-api/verify-contracts/etherscan-plugins/plugins-5.webp
Labels: A2 - Maintenance Minor

#928 Update language selector script
  js/handleLanguageChange.js
Labels: A1 - Maintenance Major

#940 Decom state of the dapps
  images/learn/dapps-list/state-of-the-dapps/state-of-the-dapps-1.webp
  images/learn/dapps-list/state-of-the-dapps/state-of-the-dapps-2.webp
  learn/dapps-list/.pages
  learn/dapps-list/state-of-the-dapps.md
Labels: A2 - Maintenance Minor

#943 add xcWIFD and xcNCTR
  builders/interoperability/xcm/xc20/overview.md
Labels: A3 - Quick Fixes

#945 Block gas limit and async backing updates for Moonriver
  .snippets/text/_common/async-backing-moonbase.md
  .snippets/text/_common/async-backing.md
  builders/build/runtime-upgrades.md
  builders/interoperability/xcm/core-concepts/weights-fees.md
  builders/interoperability/xcm/remote-execution/remote-evm-calls.md
  learn/features/governance.md
  learn/features/staking.md
  learn/features/treasury.md
  learn/platform/networks/moonbase.md
  learn/platform/networks/moonriver.md
  node-operators/networks/collators/activities.md
  variables.yml
Labels: A2 - Maintenance Minor
