Repository moonbeam-foundation/moonbeam-docs, pull requests merged in 2024-10, with the labels that each got.

#999 Add Finalized and Safe Block tags
  builders/ethereum/json-rpc/eth-rpc.md
Labels: A2 - Maintenance Minor

#1003 Updates from SEO report
  .snippets/text/builders/interoperability/xcm/xc20/send-xc20s/overview/DOT-to-xcDOT-instructions.md
  .snippets/text/builders/interoperability/xcm/xc20/send-xc20s/overview/xcDOT-to-DOT-instructions.md
  .snippets/text/node-operators/networks/run-a-node/sql-backend.md
  builders/ethereum/dev-env/hardhat.md
  builders/ethereum/dev-env/remix.md
  builders/ethereum/dev-env/thirdweb.md
  builders/ethereum/dev-env/waffle-mars.md
  builders/ethereum/json-rpc/debug-trace.md
  builders/ethereum/precompiles/features/randomness.md
  builders/ethereum/precompiles/ux/batch.md
  builders/ethereum/verify-contracts/api-verification.md
  builders/get-started/networks/moonbeam-dev.md
  builders/get-started/quick-start.md
  builders/integrations/oracles/supra.md
  builders/interoperability/mrl.md
  builders/interoperability/xcm/remote-execution/computed-origins.md
  builders/interoperability/xcm/remote-execution/overview.md
  builders/interoperability/xcm/remote-execution/remote-evm-calls.md
  builders/interoperability/xcm/remote-execution/substrate-calls/xcm-transactor-pallet.md
  builders/interoperability/xcm/remote-execution/substrate-calls/xcm-transactor-precompile.md
  builders/interoperability/xcm/send-execute-xcm.md
  builders/interoperability/xcm/xc-registration/assets.md
  builders/interoperability/xcm/xc-registration/xc-integration.md
  builders/interoperability/xcm/xc20/overview.md
  builders/interoperability/xcm/xc20/send-xc20s/eth-api.md
  builders/interoperability/xcm/xc20/send-xc20s/overview.md
  builders/interoperability/xcm/xc20/send-xc20s/xtokens-pallet.md
  learn/core-concepts/consensus-finality.md
  learn/features/eth-compatibility.md
  learn/features/xchain-plans.md
  learn/platform/networks/moonbeam.md
  learn/platform/networks/moonriver.md
  learn/platform/technology.md
  learn/platform/tokens.md
  node-operators/networks/run-a-node/docker.md
  node-operators/networks/run-a-node/systemd.md
  tokens/connect/coinbase-wallet.md
  tokens/connect/metamask.md
  tokens/connect/talisman.md
  tutorials/eth-api/foundry-start-to-end.md
  tutorials/eth-api/randomness-lottery.md
  tutorials/eth-api/thirdweb.md
  tutorials/integrations/supra.md
  tutorials/interoperability/remote-batched-evm-calls.md
  tutorials/interoperability/uniswapv2-swap-xcm.md
Labels: A2 - Maintenance Minor

#1004 Add Moonbeam Safe Video to Safe Docs
  tokens/manage/multisig-safe.md
Labels: A3 - Quick Fixes

#1006 RT 3200 and v0.40.1 client upgrades
  .snippets/code/builders/get-started/networks/moonbeam-dev/terminal/docker-pull.md
  .snippets/code/builders/get-started/networks/moonbeam-dev/terminal/docker-run.md
  builders/build/runtime-upgrades.md
  variables.yml
Labels: A2 - Maintenance Minor

#1009 Moonbase 3300 Changes
  builders/build/runtime-upgrades.md
  builders/interoperability/xcm/remote-execution/remote-evm-calls.md
  variables.yml
Labels: A3 - Quick Fixes

#1005 Add P256Verify Precompile
  .snippets/code/builders/ethereum/precompiles/utility/eth-mainnet/p256verify.sol
  .snippets/code/builders/ethereum/precompiles/utility/eth-mainnet/p256verifywithtests.sol
  .snippets/text/builders/ethereum/canonical-contracts/eth-mainnet.md
  builders/ethereum/precompiles/utility/eth-mainnet.md
Labels: A1 - Maintenance Major

#1001 New Weights, RefTime, ProofSize, RocksDB changes
  .snippets/code/builders/interoperability/xcm/core-concepts/weights-fees/query-acceptable-payment-assets.js
  .snippets/code/builders/interoperability/xcm/core-concepts/weights-fees/query-xcm-weight.js
  .snippets/code/builders/interoperability/xcm/core-concepts/weights-fees/weight-to-asset-fee-conversion.js
  .snippets/code/builders/interoperability/xcm/send-execute-xcm/execute/execute-with-polkadot.js
  .snippets/code/builders/interoperability/xcm/send-execute-xcm/execute/generate-encoded-calldata.js
  builders/interoperability/xcm/core-concepts/weights-fees.md
  builders/interoperability/xcm/send-execute-xcm.md
  builders/interoperability/xcm/xc20/send-xc20s/xtokens-pallet.md
  learn/core-concepts/tx-fees.md
  variables.yml
Labels: A1 - Maintenance Major

#1011 Moonbeam 3200 Runtime Upgrade
  builders/build/runtime-upgrades.md
  variables.yml
Labels: A3 - Quick Fixes

#978 Dawn/non specific precompiles
  .snippets/code/builders/ethereum/precompiles/utility/eth-mainnet/sha3fips.sol
  .snippets/code/builders/ethereum/precompiles/utility/nonspecific/RecoverPublicKey.sol
  .snippets/code/builders/ethereum/precompiles/utility/nonspecific/signMessage.js
  .snippets/code/builders/ethereum/precompiles/utility/nonspecific/terminal/signature.md
  .snippets/text/builders/ethereum/canonical-contracts/non-specific.md
  builders/ethereum/precompiles/utility/.pages
  builders/ethereum/precompiles/utility/eth-mainnet.md
  builders/ethereum/precompiles/utility/non-specific.md
  images/builders/ethereum/precompiles/utility/nonspecific/nonspecific-1.webp
Labels: A0 - New Content
