Repository moonbeam-foundation/moonbeam-docs, pull requests merged in 2025-05, with the labels that each got.

#1126 Moonbeam Runtime 3600 - Modify Min Collator Self Stake
  variables.yml
Labels: A3 - Quick Fixes, B1 - Ready to Merge

#1137 Remove Element from ReadMe
  README.md
Labels: A3 - Quick Fixes, B0 - Needs Review

#1135 Added new js files from Mkdocs main.html
  js/clipboardCopyllms.js
  js/connectMetaMask.js
  js/cookbookEventHandler.js
  js/cookbookInit.js
Labels: A2 - Maintenance Minor, B1 - Ready to Merge

#1141 Update clipboardCopyllms.js
  js/clipboardCopyllms.js
Labels: A3 - Quick Fixes, B0 - Needs Review
