Repository moonbeam-foundation/moonbeam-docs, pull requests merged in 2025-01, with the labels that each got.

#1041 fix 404s - December
  builders/get-started/networks/moonbase.md
  builders/integrations/oracles/api3.md
  builders/integrations/oracles/dia.md
  builders/integrations/oracles/supra.md
  node-operators/networks/collators/orbiter.md
Labels: A2 - Maintenance Minor

#1059 Runtime Upgrade 3400 Moonriver
  builders/build/runtime-upgrades.md
  builders/interoperability/xcm/core-concepts/weights-fees.md
  variables.yml
Labels: A3 - Quick Fixes

#1053 Update Scaffold Eth Tutorial
  .snippets/code/builders/ethereum/dev-env/scaffold-eth/terminal/account-import.md
  .snippets/code/builders/ethereum/dev-env/scaffold-eth/terminal/compile.md
  .snippets/code/builders/ethereum/dev-env/scaffold-eth/terminal/deploy.md
  .snippets/code/builders/ethereum/dev-env/scaffold-eth/terminal/start.md
  .snippets/code/builders/ethereum/dev-env/scaffold-eth/terminal/verify.md
  builders/ethereum/dev-env/scaffold-eth.md
  images/builders/ethereum/dev-env/scaffold-eth/new/scaffold-eth-1.webp
  images/builders/ethereum/dev-env/scaffold-eth/new/scaffold-eth-2.webp
  images/builders/ethereum/dev-env/scaffold-eth/new/scaffold-eth-3.webp
  images/builders/ethereum/dev-env/scaffold-eth/new/scaffold-eth-4.webp
  images/builders/ethereum/dev-env/scaffold-eth/new/scaffold-eth-5.webp
Labels: A2 - Maintenance Minor

#1058 Modernize Randomness Lottery Tutorial
  .snippets/code/tutorials/eth-api/randomness-lottery/terminal/compile.md
  .snippets/code/tutorials/eth-api/randomness-lottery/terminal/deploy.md
  .snippets/code/tutorials/eth-api/randomness-lottery/terminal/participate.md
  images/tutorials/eth-api/randomness-lottery/lottery-2.webp
  images/tutorials/eth-api/randomness-lottery/lottery-3.webp
  images/tutorials/eth-api/randomness-lottery/lottery-4.webp
  tutorials/eth-api/randomness-lottery.md
Labels: A2 - Maintenance Minor

#1056 Modernize Batch Swap Tutorial
  .snippets/code/tutorials/eth-api/batch-approve-swap/terminal/compile.md
  .snippets/code/tutorials/eth-api/batch-approve-swap/terminal/deploy.md
  .snippets/code/tutorials/eth-api/batch-approve-swap/terminal/swap.md
  images/tutorials/eth-api/batch-approve-swap/batch-1.webp
  images/tutorials/eth-api/batch-approve-swap/batch-2.webp
  images/tutorials/eth-api/batch-approve-swap/batch-3.webp
  tutorials/eth-api/batch-approve-swap.md
Labels: A2 - Maintenance Minor

#1061 add file path (~$) to terminal elements
  .snippets/code/tutorials/eth-api/batch-approve-swap/terminal/compile.md
  .snippets/code/tutorials/eth-api/batch-approve-swap/terminal/deploy.md
  .snippets/code/tutorials/eth-api/batch-approve-swap/terminal/swap.md
  .snippets/code/tutorials/eth-api/randomness-lottery/terminal/compile.md
  .snippets/code/tutorials/eth-api/randomness-lottery/terminal/deploy.md
  .snippets/code/tutorials/eth-api/randomness-lottery/terminal/participate.md
Labels: A3 - Quick Fixes

#1057 Create CODEOWNERS
  .github/CODEOWNERS
Labels: A2 - Maintenance Minor

#1054 Quick Hardhat Updates
  builders/ethereum/dev-env/hardhat.md
  tutorials/eth-api/hardhat-start-to-end.md
Labels: A3 - Quick Fixes

#1044 Add migration for referenda deposits to historical updates page
  builders/build/historical-updates.md
Labels: A2 - Maintenance Minor

#1060 Gas Var updates
  .snippets/code/builders/ethereum/json-rpc/debug-trace/terminal/start-up-logs.md
  .snippets/code/builders/get-started/networks/moonbeam-dev/terminal/sidecar.md
  builders/get-started/networks/moonbase.md
Labels: A3 - Quick Fixes

#1063 Polkadot.Network links migration to Polkadot.com
  .snippets/text/node-operators/networks/collators/account-management/generate-session-keys.md
  builders/get-started/quick-start.md
  learn/features/governance.md
  learn/platform/links.md
  learn/platform/networks/moonbase.md
Labels: A3 - Quick Fixes

#1040 Freshen up Graph Docs
  .snippets/code/builders/integrations/indexers/thegraph/example-query.js
  .snippets/code/builders/integrations/indexers/thegraph/terminal/create-subgraph.md
  .snippets/code/builders/integrations/indexers/thegraph/terminal/graph-auth.md
  .snippets/code/builders/integrations/indexers/thegraph/terminal/graph-deploy.md
  builders/integrations/indexers/thegraph.md
Labels: A2 - Maintenance Minor, B1 - Ready to be Merged

#1043 Adds EVM contract metadata migration to historical updates page
  builders/build/historical-updates.md
  builders/build/runtime-upgrades.md
Labels: A2 - Maintenance Minor, B1 - Ready to be Merged

#1064 refresh subsquid indexer tutorial
  .snippets/code/tutorials/integrations/local-subsquid/terminal/compile.md
  .snippets/code/tutorials/integrations/local-subsquid/terminal/deploy.md
  .snippets/code/tutorials/integrations/local-subsquid/terminal/squid-commands.md
  .snippets/code/tutorials/integrations/local-subsquid/terminal/start-node.md
  .snippets/code/tutorials/integrations/local-subsquid/terminal/transaction.md
  .snippets/code/tutorials/integrations/local-subsquid/terminal/typegen.md
  images/tutorials/integrations/local-subsquid/new/local-squid-1.webp
  images/tutorials/integrations/local-subsquid/new/local-squid-2.webp
  images/tutorials/integrations/local-subsquid/new/local-squid-3.webp
  images/tutorials/integrations/local-subsquid/new/local-squid-4.webp
  images/tutorials/integrations/local-subsquid/new/local-squid-5.webp
  images/tutorials/integrations/local-subsquid/new/local-squid-6.webp
  images/tutorials/integrations/local-subsquid/new/local-squid-7.webp
  tutorials/integrations/local-subsquid.md
Labels: A2 - Maintenance Minor, B1 - Ready to be Merged

#1068 update moongas image to reflect new fees
  images/builders/get-started/networks/moonbase/moonbase-8.webp
Labels: A3 - Quick Fixes, B1 - Ready to be Merged

#1071 Gov Revisions
  .snippets/text/learn/features/governance/approval-support-definitions.md
  .snippets/text/learn/features/governance/delegation-definitions.md
  .snippets/text/learn/features/governance/lead-in-definitions.md
  .snippets/text/learn/features/governance/preimage-definitions.md
  .snippets/text/learn/features/governance/proposal-definitions.md
  .snippets/text/learn/features/governance/vote-conviction-definitions.md
  learn/features/governance.md
Labels: A2 - Maintenance Minor, B1 - Ready to be Merged

#1069 Clarify governance support param
  learn/features/governance.md
Labels: A3 - Quick Fixes, B1 - Ready to be Merged

#1077 Moonbase Runtime Upgrade
  builders/build/runtime-upgrades.md
  variables.yml
Labels: A3 - Quick Fixes, B0 - Needs Review

#1080 Typo Fix
  learn/dapps-list/dapp-directory.md
Labels: A3 - Quick Fixes, B0 - Needs Review

#1062 Ape Changes
  .snippets/code/builders/ethereum/dev-env/ape/ape-config.yaml
  .snippets/code/builders/ethereum/dev-env/ape/terminal/retrieve.md
  builders/ethereum/dev-env/ape.md
Labels: A1 - Maintenance Major, B1 - Ready to be Merged

#1065 LayerZero Link Updates
  builders/interoperability/protocols/layerzero.md
Labels: A3 - Quick Fixes, B1 - Ready to be Merged

#1066 Waffle and Mars Modernize
  .snippets/code/builders/ethereum/dev-env/waffle-mars/terminal/build-1.md
  .snippets/code/builders/ethereum/dev-env/waffle-mars/terminal/build-2.md
  .snippets/code/builders/ethereum/dev-env/waffle-mars/terminal/deploy-1.md
  .snippets/code/builders/ethereum/dev-env/waffle-mars/terminal/deploy-2.md
  builders/ethereum/dev-env/waffle-mars.md
  images/builders/ethereum/dev-env/waffle-mars/waffle-mars-1.webp
  images/builders/ethereum/dev-env/waffle-mars/waffle-mars-2.webp
  images/builders/ethereum/dev-env/waffle-mars/waffle-mars-3.webp
  images/builders/ethereum/dev-env/waffle-mars/waffle-mars-4.webp
  images/builders/ethereum/dev-env/waffle-mars/waffle-mars-5.webp
Labels: A2 - Maintenance Minor, B1 - Ready to be Merged

#1067 Decommission XTokens Pallet Docs
  builders/interoperability/mrl.md
  builders/interoperability/xcm/core-concepts/instructions.md
  builders/interoperability/xcm/overview.md
  builders/interoperability/xcm/remote-execution/overview.md
  builders/interoperability/xcm/remote-execution/remote-evm-calls.md
  builders/interoperability/xcm/send-execute-xcm.md
  builders/interoperability/xcm/xc20/overview.md
  builders/interoperability/xcm/xc20/send-xc20s/.pages
  builders/interoperability/xcm/xc20/send-xc20s/overview.md
  builders/interoperability/xcm/xc20/send-xc20s/xcm-pallet.md
  builders/interoperability/xcm/xc20/send-xc20s/xtokens-precompile.md
  builders/substrate/interfaces/interoperability/.pages
Labels: A2 - Maintenance Minor, B1 - Ready to be Merged

#1072 Decomission Metafab
  builders/integrations/.pages
  builders/integrations/gaming/.pages
  builders/integrations/gaming/index.md
  builders/integrations/gaming/metafab.md
  images/builders/integrations/gaming/metafab/metafab-1.webp
  images/builders/integrations/gaming/metafab/metafab-2.webp
  images/builders/integrations/gaming/metafab/metafab-3.webp
  images/builders/integrations/gaming/metafab/metafab-4.webp
Labels: A3 - Quick Fixes, B1 - Ready to be Merged

#1074 Remove Units Per Second
  .snippets/code/builders/interoperability/xcm/core-concepts/weights-fees/units-per-second.js
  .snippets/code/builders/interoperability/xcm/remote-execution/substrate-calls/xcm-transactor-pallet/calculate-relative-price.ts
  .snippets/code/builders/interoperability/xcm/remote-execution/substrate-calls/xcm-transactor-pallet/destination-asset-fee-per-second.js
  builders/interoperability/xcm/core-concepts/weights-fees.md
  builders/interoperability/xcm/remote-execution/substrate-calls/xcm-transactor-pallet.md
  builders/interoperability/xcm/remote-execution/substrate-calls/xcm-transactor-precompile.md
  builders/interoperability/xcm/xcm-utils.md
Labels: A1 - Maintenance Major, B1 - Ready to be Merged

#1075 Update ReadMe Image
  images/readme-contributing/readme-banner.webp
Labels: A3 - Quick Fixes, B1 - Ready to be Merged

#1070 Block Upgrade Revision
  builders/build/historical-updates.md
  builders/build/runtime-upgrades.md
Labels: A3 - Quick Fixes, B1 - Ready to be Merged

#1079 changed chain specs link for alphanet relay
  builders/interoperability/xcm/xc-registration/xc-integration.md
Labels: A3 - Quick Fixes, B1 - Ready to be Merged

#1083 Debug Block Revisions
  builders/ethereum/json-rpc/debug-trace.md
  builders/get-started/quick-start.md
Labels: A2 - Maintenance Minor, B1 - Ready to be Merged

#1081 added new xc20 to Moonbeam
  builders/interoperability/xcm/xc20/overview.md
Labels: A3 - Quick Fixes, B1 - Ready to be Merged

#1085 Changed the RPC endpoint for Polkadot.js Apps Treasury account on Moonbase Alpha
  tokens/governance/treasury-spend.md
Labels: A3 - Quick Fixes, B1 - Ready to be Merged

#1088 Runtime 3400 Moonbeam Gas Updates
  .snippets/code/builders/integrations/indexers/covalent/get-a-transaction/response.sh
  .snippets/code/builders/integrations/indexers/covalent/get-bulk-time/response.sh
  .snippets/code/builders/integrations/indexers/covalent/recent-transactions/response.sh
  .snippets/code/builders/integrations/oracles/supra/terminal/output.md
  .snippets/code/learn/core-concepts/tx-fees/tx-fees-block-dynamic.js
  .snippets/code/tutorials/integrations/supra/terminal/transaction-receipt.md
  learn/core-concepts/tx-fees.md
  variables.yml
Labels: A2 - Maintenance Minor, B1 - Ready to be Merged
