Repository moonbeam-foundation/moonbeam-docs, pull requests merged in 2025-02, with the labels that each got.

#1090 Added the Moonbeam Runtime 3400 creation Block and changed weights-fees links to GH
  builders/build/runtime-upgrades.md
  builders/interoperability/xcm/core-concepts/weights-fees.md
Labels: A3 - Quick Fixes, B1 - Ready to be Merged

#1095 Typos
  builders/ethereum/precompiles/ux/batch.md
  builders/get-started/endpoints.md
  builders/interoperability/mrl.md
  builders/interoperability/xcm/core-concepts/weights-fees.md
  builders/interoperability/xcm/xc-registration/xc-integration.md
  node-operators/networks/run-a-node/flags.md
Labels: A3 - Quick Fixes, B1 - Ready to be Merged

#1096 Snippets for Run a Node
  .snippets/code/node-operators/networks/run-a-node/docker/terminal/logs.md
  .snippets/code/node-operators/networks/run-a-node/docker/terminal/start.md
  .snippets/code/node-operators/networks/run-a-node/systemd/terminal/logs.md
  .snippets/code/node-operators/networks/run-a-node/systemd/terminal/status.md
  images/node-operators/networks/run-a-node/docker/full-node-docker-1.webp
  images/node-operators/networks/run-a-node/docker/full-node-docker-2.webp
  images/node-operators/networks/run-a-node/systemd/systemd-1.webp
  images/node-operators/networks/run-a-node/systemd/systemd-2.webp
  node-operators/networks/run-a-node/docker.md
  node-operators/networks/run-a-node/systemd.md
Labels: A2 - Maintenance Minor, B1 - Ready to be Merged

#1013 New XC Asset Registration Process
  .snippets/code/builders/interoperability/xcm/xc-registration/assets/calculate-relative-price.ts
  .snippets/code/builders/interoperability/xcm/xc-registration/assets/terminal/calculate-relative-price.md
  .snippets/code/builders/interoperability/xcm/xc-registration/assets/terminal/register-asset.md
  .snippets/code/builders/interoperability/xcm/xc-registration/assets/weight-trader.js
  .snippets/code/builders/interoperability/xcm/xc-registration/integration/terminal/accept.md
  .snippets/code/builders/interoperability/xcm/xc-registration/integration/terminal/propose.md
  builders/interoperability/xcm/xc-registration/assets.md
  builders/interoperability/xcm/xc-registration/xc-integration.md
  images/builders/interoperability/xcm/xc-registration/assets/assets-3.webp
Labels: A1 - Maintenance Major, B1 - Ready to Merge

#1073 relocate substrate page from Builders to learn
  builders/substrate/overview.md
  learn/platform/technology.md
Labels: A1 - Maintenance Major, B1 - Ready to Merge

#1099 Update Moonbeam Custom API Methods
  builders/ethereum/json-rpc/moonbeam-custom-api.md
Labels: A2 - Maintenance Minor, B1 - Ready to Merge

#1098 Fix Snippets
  .snippets/text/builders/interoperability/xcm/calculate-computed-origin-account.md
  builders/interoperability/xcm/xc20/interact.md
  builders/interoperability/xcm/xc20/send-xc20s/eth-api.md
  tutorials/eth-api/batch-approve-swap.md
  tutorials/interoperability/remote-batched-evm-calls.md
  tutorials/interoperability/remote-staking-xcm.md
  tutorials/interoperability/uniswapv2-swap-xcm.md
Labels: A2 - Maintenance Minor, B0 - Needs Review

#1100 Add Parameters Pallet
  .snippets/code/builders/pallets-precompiles/pallets/parameters/get-storage-item.js
  .snippets/code/builders/pallets-precompiles/pallets/parameters/pallet-version.js
  .snippets/code/builders/pallets-precompiles/pallets/parameters/set-parameter.js
  builders/substrate/interfaces/features/governance/.pages
  builders/substrate/interfaces/features/governance/parameters.md
Labels: A0 - New Content, B1 - Ready to Merge

#1103 Add Chainstack to RPC node providers
  builders/get-started/endpoints.md
  images/builders/get-started/endpoints/endpoints-7.webp
Labels: A0 - New Content, B0 - Needs Review, C1 - Medium
